## Mount google drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import json

with open("/content/drive/MyDrive/[PUB] India_runs_data_and_ai_challenge/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/candidates.jsonl", "r", encoding="utf-8") as f:
    first = json.loads(next(f))

print(first["candidate_id"])
print(first["profile"]["current_title"])

CAND_0000001
Backend Engineer

In [3]:
link = "/content/drive/MyDrive/[PUB] India_runs_data_and_ai_challenge/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/candidates.jsonl"

# Count job titles

In [4]:
import json
from collections import Counter

titles = Counter()

with open(link, "r", encoding="utf-8") as f:
    for line in f:
        candidate = json.loads(line)

        title = candidate["profile"]["current_title"]

        titles[title] += 1

print("Unique Titles:", len(titles))

for title, count in titles.most_common(30):
    print(f"{title}: {count}")

Unique Titles: 47
Business Analyst: 5833
HR Manager: 5830
Mechanical Engineer: 5791
Accountant: 5764
Project Manager: 5754
Customer Support: 5750
Operations Manager: 5744
Content Writer: 5727
Sales Executive: 5713
Civil Engineer: 5702
Graphic Designer: 5689
Marketing Manager: 5524
Software Engineer: 3450
Full Stack Developer: 2873
Cloud Engineer: 2836
Java Developer: 2809
.NET Developer: 2788
DevOps Engineer: 2787
Mobile Developer: 2757
Frontend Engineer: 2738
QA Engineer: 2682
Analytics Engineer: 764
Data Engineer: 744
Data Analyst: 728
Backend Engineer: 704
Senior Data Engineer: 687
Senior Software Engineer: 653
ML Engineer: 167
AI Research Engineer: 153
Data Scientist: 145

In [5]:
import json

target_titles = [
    "ML Engineer",
    "AI Research Engineer",
    "Data Scientist"
]

with open(link, "r", encoding="utf-8") as f:

    for line in f:

        candidate = json.loads(line)

        title = candidate["profile"]["current_title"]

        if title in target_titles:

            print("="*100)
            print("TITLE:", title)
            print("SUMMARY:")
            print(candidate["profile"]["summary"])

            print("\nSKILLS:")
            print([s["name"] for s in candidate["skills"][:10]])

            print("\nFIRST CAREER ENTRY:")
            print(candidate["career_history"][0]["description"])

            break

====================================================================================================
TITLE: ML Engineer
SUMMARY:
Data scientist / ML engineer with 4.3 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've spent the last couple of years building NLP-based classification and information extraction pipelines. I'm strongest at the modeling and analysis side; comfortable with Python, scikit-learn, pandas, and standard MLOps tooling, but I'm still building depth on the engineering and infra side of production ML. I want to grow into senior AI engineering — get serious about LLMs and retrieval beyond the surface level.

SKILLS:
['BigQuery', 'Vector Search', 'Prompt Engineering', 'BentoML', 'LlamaIndex', 'FAISS', 'RAG', 'Object Detection', 'Kubernetes', 'TTS']

FIRST CAREER ENTRY:
Worked on customer-facing predictive modeling for an e-commerce platform — churn prediction, conversion likelihood, lifetime value estimation. Used scikit-learn and XGBoost; main models were gradient-boosted trees with ~80 hand-engineered features. The work was split roughly 60/40 between modeling and data prep / SQL. The churn model is now used by the retention team, though my role was more on the modeling side than the productionization.

# Candidate Text (for every candidate)

In [6]:
import json
import pandas as pd

data = []

with open(link, "r", encoding="utf-8") as f:

    for line in f:

        candidate = json.loads(line)

        # Basic Profile
        candidate_id = candidate["candidate_id"]

        title = candidate["profile"]["current_title"]

        headline = candidate["profile"]["headline"]

        summary = candidate["profile"]["summary"]

        experience = candidate["profile"]["years_of_experience"]

        # Skills
        skills = " ".join(
            [skill["name"] for skill in candidate["skills"]]
        )

        # Career History
        career_text = " ".join(
            [job["description"] for job in candidate["career_history"]]
        )

        # Final Candidate Text
        candidate_text = (
            headline
            + " "
            + summary
            + " "
            + title
            + " "
            + skills
            + " "
            + career_text
        )

        data.append({
            "candidate_id": candidate_id,
            "title": title,
            "experience": experience,
            "candidate_text": candidate_text
        })

df = pd.DataFrame(data)

print(df.head())

   candidate_id               title  experience  \
0  CAND_0000001    Backend Engineer         6.9
1  CAND_0000002  Operations Manager        12.5
2  CAND_0000003    Customer Support         1.1
3  CAND_0000004   Marketing Manager         3.8
4  CAND_0000005          Accountant        11.0

                                      candidate_text
0  Backend Engineer | SQL, Spark, Cloud Software ...
1  Operations Manager | 12.5+ yrs experience Prof...
2  Customer Support | 1.1+ yrs experience Profess...
3  Marketing Manager | Driving business outcomes ...
4  Accountant | Helping teams scale Professional ...

In [7]:
import json
from collections import Counter

titles = Counter()

with open(link, "r", encoding="utf-8") as f:
    for line in f:
        candidate = json.loads(line)
        titles[candidate["profile"]["current_title"]] += 1

# Show titles containing AI/ML/Data keywords
for title, count in sorted(titles.items()):
    if any(k in title.lower() for k in [
        "ai", "ml", "machine learning",
        "data scientist", "data engineer",
        "analytics", "backend", "software"
    ]):
        print(f"{title}: {count}")

AI Engineer: 21
AI Research Engineer: 153
AI Specialist: 130
Analytics Engineer: 764
Applied ML Engineer: 23
Backend Engineer: 704
Data Engineer: 744
Data Scientist: 145
Junior ML Engineer: 131
Lead AI Engineer: 3
ML Engineer: 167
Machine Learning Engineer: 24
Senior AI Engineer: 4
Senior Data Engineer: 687
Senior Data Scientist: 19
Senior Machine Learning Engineer: 6
Senior Software Engineer: 653
Senior Software Engineer (ML): 142
Software Engineer: 3450
Staff Machine Learning Engineer: 6

In [8]:
import json

target_titles = [
    "ML Engineer",
    "AI Research Engineer",
    "Backend Engineer",
    "Data Engineer",
    "Marketing Manager"
]

found = set()

with open(link, "r", encoding="utf-8") as f:

    for line in f:

        c = json.loads(line)

        title = c["profile"]["current_title"]

        if title in target_titles and title not in found:

            print("="*100)
            print("TITLE:", title)

            print("\nSUMMARY:")
            print(c["profile"]["summary"])

            print("\nSKILLS:")
            print([s["name"] for s in c["skills"][:10]])

            print("\nCAREER:")
            print(c["career_history"][0]["description"])

            found.add(title)

        if len(found) == len(target_titles):
            break

====================================================================================================
TITLE: Backend Engineer

SUMMARY:
Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.

SKILLS:
['Tailwind', 'NLP', 'Image Classification', 'Fine-tuning LLMs', 'Weights & Biases', 'Speech Recognition', 'Photoshop', 'TTS', 'LoRA', 'Apache Beam']

CAREER:
Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure.
====================================================================================================
TITLE: Marketing Manager

SUMMARY:
Professional with 3.8+ years of experience. My professional background is in marketing manager — I've built and led teams, owned KPIs, and driven business outcomes in this domain. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.

SKILLS:
['Node.js', 'Content Writing', 'Redux', 'Airflow', 'GraphQL', 'Object Detection', 'Webpack', 'Six Sigma', 'SAP', 'JavaScript']

CAREER:
Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the typical hardware-development cadence. Worked closely with manufacturing partners on production scale-up.
====================================================================================================
TITLE: Data Engineer

SUMMARY:
Software / data professional with 4.6 years of experience building data pipelines, backend systems, and analytics infrastructure. Most of my work has been data pipelines and analytics infrastructure; I've shipped a couple of small ML features but it's not the core of my day. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.

SKILLS:
['GCP', 'Spring Boot', 'Kubeflow', 'Java', 'GANs', 'Figma', 'Elasticsearch', 'OpenCV', 'CNN', 'Azure']

CAREER:
Mixed data science and analytics-engineering role at a marketing-analytics startup. Spent maybe 30% of my time on lightweight ML (clustering, classification, churn prediction in sklearn/XGBoost) and 70% on data infrastructure and dashboards. Comfortable with the modeling work but I wouldn't call myself an ML specialist. Built our experimentation framework that supports the product team's A/B tests.
====================================================================================================
TITLE: ML Engineer

SUMMARY:
Data scientist / ML engineer with 4.3 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've spent the last couple of years building NLP-based classification and information extraction pipelines. I'm strongest at the modeling and analysis side; comfortable with Python, scikit-learn, pandas, and standard MLOps tooling, but I'm still building depth on the engineering and infra side of production ML. I want to grow into senior AI engineering — get serious about LLMs and retrieval beyond the surface level.

SKILLS:
['BigQuery', 'Vector Search', 'Prompt Engineering', 'BentoML', 'LlamaIndex', 'FAISS', 'RAG', 'Object Detection', 'Kubernetes', 'TTS']

CAREER:
Worked on customer-facing predictive modeling for an e-commerce platform — churn prediction, conversion likelihood, lifetime value estimation. Used scikit-learn and XGBoost; main models were gradient-boosted trees with ~80 hand-engineered features. The work was split roughly 60/40 between modeling and data prep / SQL. The churn model is now used by the retention team, though my role was more on the modeling side than the productionization.
====================================================================================================
TITLE: AI Research Engineer

SUMMARY:
Data scientist / ML engineer with 6.3 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. My current role is split between dashboarding/analytics and shipping production ML models. I'm strongest at the modeling and analysis side; comfortable with Python, scikit-learn, pandas, and standard MLOps tooling, but I'm still building depth on the engineering and infra side of production ML. Looking for a role where I can step up to more end-to-end ownership of ML systems, not just modeling.

SKILLS:
['MLflow', 'Python', 'Photoshop', 'Milvus', 'Java', 'OpenCV', 'Learning to Rank', 'OpenSearch', 'CNN', 'YOLO']

CAREER:
Built NLP pipelines for sentiment analysis and document classification — primarily for an internal feedback-analytics dashboard. Started with sklearn-based bag-of-words models, then moved to transformer-based classifiers (DistilBERT) for the harder classes. Comfortable with PyTorch and Hugging Face but most of my training experience has been on small datasets and pre-trained model fine-tuning, not from-scratch model design.

In [9]:

import json
import pandas as pd

rows = []

with open(link, "r", encoding="utf-8") as f:

    for line in f:

        c = json.loads(line)

        rows.append({
            "candidate_id": c["candidate_id"],
            "title": c["profile"]["current_title"],
            "experience": c["profile"]["years_of_experience"],
            "response_rate": c["redrob_signals"]["recruiter_response_rate"],
            "github_score": c["redrob_signals"]["github_activity_score"]
        })

df = pd.DataFrame(rows)

print(df.head())
print(df.shape)

   candidate_id               title  experience  response_rate  github_score
0  CAND_0000001    Backend Engineer         6.9           0.34           9.2
1  CAND_0000002  Operations Manager        12.5           0.29          -1.0
2  CAND_0000003    Customer Support         1.1           0.46          -1.0
3  CAND_0000004   Marketing Manager         3.8           0.26          -1.0
4  CAND_0000005          Accountant        11.0           0.37          -1.0
(100000, 5)

# Create career score

In [10]:
import json
import pandas as pd

candidate_texts = []

with open(link, "r", encoding="utf-8") as f:

    for line in f:

        c = json.loads(line)

        skills = " ".join(
            [s["name"] for s in c["skills"]]
        )

        career = " ".join(
            [job["description"]
             for job in c["career_history"]]
        )

        text = f"""
        {c['profile']['headline']}
        {c['profile']['summary']}
        {c['profile']['current_title']}
        {skills}
        {career}
        """

        candidate_texts.append({
            "candidate_id": c["candidate_id"],
            "candidate_text": text
        })

candidate_text_df = pd.DataFrame(candidate_texts)

print(candidate_text_df.shape)
candidate_text_df.head()

(100000, 2)

   candidate_id                                     candidate_text
0  CAND_0000001  \n        Backend Engineer | SQL, Spark, Cloud...
1  CAND_0000002  \n        Operations Manager | 12.5+ yrs exper...
2  CAND_0000003  \n        Customer Support | 1.1+ yrs experien...
3  CAND_0000004  \n        Marketing Manager | Driving business...
4  CAND_0000005  \n        Accountant | Helping teams scale\n  ...

In [11]:
print(candidate_text_df.iloc[0]["candidate_text"][:1000])

        Backend Engineer | SQL, Spark, Cloud
        Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.
        Backend Engineer
        Tailwind NLP Image Classification Fine-tuning LLMs Weights & Biases Speech Recognition Photoshop TTS LoRA Apache Beam AWS Flask BentoML Milvus GANs Statistical Modeling GCP
        Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity p

## Load sentence transformer

In [12]:
!pip install -q sentence-transformers

In [13]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:124: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

# install python docx package

In [14]:
!pip install python-docx

Collecting python-docx
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (6.1.1)
Requirement already satisfied: typing_extensions>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (4.15.0)
Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 9.1 MB/s eta 0:00:00
Installing collected packages: python-docx
Successfully installed python-docx-1.2.0

## Read job description

In [15]:
from docx import Document

doc = Document("/content/drive/MyDrive/[PUB] India_runs_data_and_ai_challenge/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/job_description.docx")

jd_text = "\n".join(
    [p.text for p in doc.paragraphs]
)

print(jd_text[:2000])

Job Description: Senior AI Engineer — Founding Team
Company: Redrob AI (Series A AI-native talent intelligence platform)
Location: Pune/Noida, India (Hybrid — flexible cadence) | Open to relocation candidates from Tier-1 Indian cities
Employment Type: Full-time
Experience Required: 5–9 years (see "what we mean by this" below)

Let's be honest about this role
We're going to write this JD differently from most. We're a Series A company that just raised our round and we're building a new AI Engineering org from scratch. This is the kind of role where the JD changes every six months because the company changes every six months. So instead of pretending we have a fixed checklist, we're going to tell you what we actually need and what we've gotten wrong before.
If you've spent your career at Google or Meta and you want a well-scoped role with a defined ladder, this isn't it.
If you've spent your career bouncing between early-stage startups and you want to "just code" without having to think about product or recruiter workflows or eval frameworks, this also isn't it.
We need someone who is simultaneously comfortable with two things that sound contradictory:
Deep technical depth in modern ML systems — embeddings, retrieval, ranking, LLMs, fine-tuning.
Scrappy product-engineering attitude — willing to ship a working ranker in a week even if the underlying ML is "obviously suboptimal," because we need to learn from real users before we know what to actually optimize for.
These are not contradictory in real life. They feel contradictory because of how engineering culture sorted itself into "researcher" vs "shipper" archetypes. We need both modes available in the same person, and we'd rather you tilt slightly toward shipper than toward researcher.

What you'd actually be doing
The high-level mandate: own the intelligence layer of Redrob's product. That means the ranking, retrieval, and matching systems that decide what recruiters see when they search for candidates and what can

## Create semantic embedding

In [16]:
jd_embedding = model.encode(
    jd_text,
    normalize_embeddings=True
)

print(jd_embedding.shape)

(384,)

In [17]:
sample_df = candidate_text_df.head(100)

candidate_embeddings = model.encode(
    sample_df["candidate_text"].tolist(),
    normalize_embeddings=True,
    show_progress_bar=True
)

print(candidate_embeddings.shape)

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

(100, 384)

## Semantic matching

In [18]:
from sklearn.metrics.pairwise import cosine_similarity

semantic_scores = cosine_similarity(
    [jd_embedding],
    candidate_embeddings
)[0]

print(semantic_scores[:10])

[0.43511003 0.59392834 0.51582325 0.50286424 0.4449983  0.5243898
 0.5405003  0.55999243 0.5381979  0.46737272]

In [19]:
sample_df["semantic_score"] = semantic_scores

/tmp/ipykernel_977/1951765358.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample_df["semantic_score"] = semantic_scores

In [20]:
print(sample_df.columns)

Index(['candidate_id', 'candidate_text', 'semantic_score'], dtype='object')

In [21]:
top10 = sample_df.sort_values(
    "semantic_score",
    ascending=False
)

top10[
    ["candidate_id", "semantic_score"]
].head(10)

    candidate_id  semantic_score
73  CAND_0000074        0.607783
92  CAND_0000093        0.599747
96  CAND_0000097        0.596781
44  CAND_0000045        0.595340
1   CAND_0000002        0.593928
20  CAND_0000021        0.591938
12  CAND_0000013        0.582155
16  CAND_0000017        0.569256
83  CAND_0000084        0.562287
40  CAND_0000041        0.561592

In [22]:
import json

target_ids = top10["candidate_id"].head(5).tolist()

with open(link, "r", encoding="utf-8") as f:

    for line in f:

        c = json.loads(line)

        if c["candidate_id"] in target_ids:

            print("="*100)

            print("TITLE:",
                  c["profile"]["current_title"])

            print()

            for job in c["career_history"]:

                print(job["description"])
                print()

====================================================================================================
TITLE: Operations Manager

Customer support team lead at a SaaS product. Managed a team of 8 support agents handling tier-1 and tier-2 tickets; owned the escalation process to engineering and the customer-feedback loop to product. Built out the support knowledge base and the agent training program. Strong on the people-management side and the process side; lighter on technical depth beyond product expertise.

Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the typical hardware-development cadence. Worked closely with manufacturing partners on production scale-up.

Content writing and SEO strategy for a tech-focused publication. Wrote longform articles on developer tools, cloud platforms, and AI/ML topics — including some that ranked on the first page of search for high-competition keywords. Managed a freelance writer pool and the editorial calendar. Recent work has been on AI-assisted content production, using LLM tools for research, drafting, and editing while maintaining editorial quality.

Brand design and creative direction at a consumer-products company. Owned brand identity (logo, visual system, typography), packaging design, and digital creative across web and social. Led the recent rebrand and managed a small external agency for production work. Comfortable across the Adobe suite, Figma, and the production side of brand and packaging design.

====================================================================================================
TITLE: Project Manager

Enterprise sales of cloud software solutions into the mid-market segment. Carried a $1.8M ARR quota and consistently delivered against it across the last three years. Owned the full sales cycle: prospecting, discovery, technical evaluation (with SE support), commercial negotiation, and close. Strong on consultative selling for technical buyers; comfortable engaging with both engineering and finance stakeholders.

Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the typical hardware-development cadence. Worked closely with manufacturing partners on production scale-up.

Customer support team lead at a SaaS product. Managed a team of 8 support agents handling tier-1 and tier-2 tickets; owned the escalation process to engineering and the customer-feedback loop to product. Built out the support knowledge base and the agent training program. Strong on the people-management side and the process side; lighter on technical depth beyond product expertise.

Marketing leadership role at a B2B SaaS company. Owned the demand-generation function — content marketing, paid acquisition, SEO, email nurture. Built and managed a team of 5 across content, performance marketing, and marketing operations. Worked closely with sales on lead-quality definitions and the SDR-handoff process. Recent focus has been on account-based marketing for our enterprise segment.

Customer support team lead at a SaaS product. Managed a team of 8 support agents handling tier-1 and tier-2 tickets; owned the escalation process to engineering and the customer-feedback loop to product. Built out the support knowledge base and the agent training program. Strong on the people-management side and the process side; lighter on technical depth beyond product expertise.

Enterprise sales of cloud software solutions into the mid-market segment. Carried a $1.8M ARR quota and consistently delivered against it across the last three years. Owned the full sales cycle: prospecting, discovery, technical evaluation (with SE support), commercial negotiation, and close. Strong on consultative selling for technical buyers; comfortable engaging with both engineering and finance stakeholders.

Enterprise sales of cloud software solutions into the mid-market segment. Carried a $1.8M ARR quota and consistently delivered against it across the last three years. Owned the full sales cycle: prospecting, discovery, technical evaluation (with SE support), commercial negotiation, and close. Strong on consultative selling for technical buyers; comfortable engaging with both engineering and finance stakeholders.

====================================================================================================
TITLE: Operations Manager

Marketing leadership role at a B2B SaaS company. Owned the demand-generation function — content marketing, paid acquisition, SEO, email nurture. Built and managed a team of 5 across content, performance marketing, and marketing operations. Worked closely with sales on lead-quality definitions and the SDR-handoff process. Recent focus has been on account-based marketing for our enterprise segment.

====================================================================================================
TITLE: Civil Engineer

Business analyst at a consulting firm, working primarily with retail and CPG clients. Conducted business diagnostics, process re-engineering work, and digital transformation strategy projects. Strong on stakeholder management, structured problem-solving, and the typical consulting toolkit (slide-craft, Excel modeling, executive communication). Recent project work involved AI-strategy advisory but my own technical depth in AI is limited.

Marketing leadership role at a B2B SaaS company. Owned the demand-generation function — content marketing, paid acquisition, SEO, email nurture. Built and managed a team of 5 across content, performance marketing, and marketing operations. Worked closely with sales on lead-quality definitions and the SDR-handoff process. Recent focus has been on account-based marketing for our enterprise segment.

Brand design and creative direction at a consumer-products company. Owned brand identity (logo, visual system, typography), packaging design, and digital creative across web and social. Led the recent rebrand and managed a small external agency for production work. Comfortable across the Adobe suite, Figma, and the production side of brand and packaging design.

Enterprise sales of cloud software solutions into the mid-market segment. Carried a $1.8M ARR quota and consistently delivered against it across the last three years. Owned the full sales cycle: prospecting, discovery, technical evaluation (with SE support), commercial negotiation, and close. Strong on consultative selling for technical buyers; comfortable engaging with both engineering and finance stakeholders.

====================================================================================================
TITLE: Mechanical Engineer

Marketing leadership role at a B2B SaaS company. Owned the demand-generation function — content marketing, paid acquisition, SEO, email nurture. Built and managed a team of 5 across content, performance marketing, and marketing operations. Worked closely with sales on lead-quality definitions and the SDR-handoff process. Recent focus has been on account-based marketing for our enterprise segment.

Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the typical hardware-development cadence. Worked closely with manufacturing partners on production scale-up.

## Production Evidence score

In [23]:
production_keywords = [
    "retrieval",
    "ranking",
    "search",
    "recommendation",
    "recommendation system",
    "vector database",
    "embedding",
    "embeddings",
    "faiss",
    "milvus",
    "pinecone",
    "weaviate",
    "qdrant",
    "opensearch",
    "elasticsearch",
    "learning to rank",
    "ab test",
    "a/b test",
    "production ml",
    "deployed"
]

In [24]:
def production_score(career_text):

    text = career_text.lower()

    hits = 0

    for keyword in production_keywords:

        if keyword in text:
            hits += 1

    return hits

In [25]:
import json
import pandas as pd

rows = []

with open(link, "r", encoding="utf-8") as f:

    for line in f:

        c = json.loads(line)

        career_text = " ".join(
            job["description"]
            for job in c["career_history"]
        )

        rows.append({

            "candidate_id":
                c["candidate_id"],

            "title":
                c["profile"]["current_title"],

            "production_score":
                production_score(
                    career_text
                )
        })

production_df = pd.DataFrame(rows)

production_df.head()

   candidate_id               title  production_score
0  CAND_0000001    Backend Engineer                 0
1  CAND_0000002  Operations Manager                 1
2  CAND_0000003    Customer Support                 0
3  CAND_0000004   Marketing Manager                 1
4  CAND_0000005          Accountant                 0

In [26]:
production_df.sort_values(
    "production_score",
    ascending=False
).head(20)

       candidate_id                            title  production_score
79386  CAND_0079387                      AI Engineer                12
44854  CAND_0044855            Senior Data Scientist                11
30952  CAND_0030953                  Search Engineer                11
55991  CAND_0055992                      AI Engineer                11
54122  CAND_0054123              Applied ML Engineer                10
57562  CAND_0057563                     NLP Engineer                10
5648   CAND_0005649            Senior Data Scientist                10
30347  CAND_0030348        Machine Learning Engineer                10
75248  CAND_0075249              Applied ML Engineer                10
1609   CAND_0001610        Machine Learning Engineer                10
81685  CAND_0081686                  Search Engineer                10
96171  CAND_0096172                     NLP Engineer                10
26531  CAND_0026532  Recommendation Systems Engineer                10
44882  CAND_0044883                      AI Engineer                10
13612  CAND_0013613        Machine Learning Engineer                10
66375  CAND_0066376              Applied ML Engineer                10
46063  CAND_0046064              Senior NLP Engineer                10
60053  CAND_0060054                      AI Engineer                10
86150  CAND_0086151  Recommendation Systems Engineer                10
71973  CAND_0071974               Senior AI Engineer                 9

In [27]:
production_df["production_score_norm"] = (
    production_df["production_score"]
    /
    production_df["production_score"].max()
)

In [28]:
production_df.head()

   candidate_id               title  production_score  production_score_norm
0  CAND_0000001    Backend Engineer                 0               0.000000
1  CAND_0000002  Operations Manager                 1               0.083333
2  CAND_0000003    Customer Support                 0               0.000000
3  CAND_0000004   Marketing Manager                 1               0.083333
4  CAND_0000005          Accountant                 0               0.000000

In [29]:
print(candidate_embeddings.shape)
print(len(df))

(100, 384)
100000

In [30]:
print(df.columns)

Index(['candidate_id', 'title', 'experience', 'response_rate', 'github_score'], dtype='object')

In [31]:
print("df columns:")
print(df.columns)

try:
    print("\nsample_df columns:")
    print(sample_df.columns)
except:
    print("sample_df not found")

df columns:
Index(['candidate_id', 'title', 'experience', 'response_rate', 'github_score'], dtype='object')

sample_df columns:
Index(['candidate_id', 'candidate_text', 'semantic_score'], dtype='object')

In [32]:
len(sample_df)

100

In [33]:
print(candidate_text_df.shape)
print(candidate_text_df.columns)

(100000, 2)
Index(['candidate_id', 'candidate_text'], dtype='object')

## Convert 1000 text into vectors(Embedding)

In [34]:
test_embeddings = model.encode(
    candidate_text_df["candidate_text"].head(1000).tolist(),
    batch_size=128,
    normalize_embeddings=True,
    show_progress_bar=True
)

print(test_embeddings.shape)

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

(1000, 384)

In [35]:
from sklearn.metrics.pairwise import cosine_similarity

semantic_scores = cosine_similarity(
    [jd_embedding],
    test_embeddings
)[0]

print(semantic_scores[:10])

[0.43511003 0.59392834 0.51582325 0.50286424 0.4449983  0.5243898
 0.5405003  0.55999243 0.5381979  0.46737272]

In [36]:
test_df = candidate_text_df.head(1000).copy()

test_df["semantic_score"] = semantic_scores

test_df.sort_values(
    "semantic_score",
    ascending=False
).head(10)

,candidate_id,candidate_text,semantic_score
329,CAND_0000330,\n Civil Engineer | Exploring AI & GenA...,0.634756
321,CAND_0000322,\n HR Manager | Exploring AI & GenAI ap...,0.634191
846,CAND_0000847,\n HR Manager | Exploring AI & GenAI ap...,0.632152
914,CAND_0000915,\n Mechanical Engineer | Exploring AI &...,0.631089
738,CAND_0000739,\n Civil Engineer | AI enthusiast | Bui...,0.628330
387,CAND_0000388,\n HR Manager | Generative AI explorer\...,0.626732
827,CAND_0000828,\n Project Manager | Generative AI expl...,0.617352
926,CAND_0000927,\n Civil Engineer | AI enthusiast | Bui...,0.614823
119,CAND_0000120,\n Graphic Designer | Exploring AI & Ge...,0.611186
73,CAND_0000074,\n Operations Manager | Generative AI e...,0.607783

In [37]:
top_prod = production_df.sort_values(
    "production_score",
    ascending=False
).head(20)

top_prod

,candidate_id,title,production_score,production_score_norm
79386,CAND_0079387,AI Engineer,12,1.000000
44854,CAND_0044855,Senior Data Scientist,11,0.916667
30952,CAND_0030953,Search Engineer,11,0.916667
55991,CAND_0055992,AI Engineer,11,0.916667
54122,CAND_0054123,Applied ML Engineer,10,0.833333
57562,CAND_0057563,NLP Engineer,10,0.833333
5648,CAND_0005649,Senior Data Scientist,10,0.833333
30347,CAND_0030348,Machine Learning Engineer,10,0.833333
75248,CAND_0075249,Applied ML Engineer,10,0.833333
1609,CAND_0001610,Machine Learning Engineer,10,0.833333
81685,CAND_0081686,Search Engineer,10,0.833333
96171,CAND_0096172,NLP Engineer,10,0.833333
26531,CAND_0026532,Recommendation Systems Engineer,10,0.833333
44882,CAND_0044883,AI Engineer,10,0.833333
13612,CAND_0013613,Machine Learning Engineer,10,0.833333
66375,CAND_0066376,Applied ML Engineer,10,0.833333
46063,CAND_0046064,Senior NLP Engineer,10,0.833333
60053,CAND_0060054,AI Engineer,10,0.833333
86150,CAND_0086151,Recommendation Systems Engineer,10,0.833333
71973,CAND_0071974,Senior AI Engineer,9,0.750000

In [38]:
target_id = "CAND_0079387"

In [39]:
import json

with open(link, "r", encoding="utf-8") as f:

    for line in f:

        c = json.loads(line)

        if c["candidate_id"] == target_id:

            print("TITLE:")
            print(c["profile"]["current_title"])

            print("\nSUMMARY:")
            print(c["profile"]["summary"])

            print("\nSKILLS:")
            print([s["name"] for s in c["skills"]])

            print("\nCAREER HISTORY:")
            for job in c["career_history"]:
                print("\n---")
                print(job["description"])

            break

TITLE:
AI Engineer

SUMMARY:
Machine learning engineer with 6.9 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I've been the de-facto ML lead on a small team, shipping models across NLP and recsys. I've learned that most retrieval problems are actually evaluation problems in disguise. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['scikit-learn', 'Recommendation Systems', 'Python', 'Time Series', 'Sentence Transformers', 'JavaScript', 'Illustrator', 'Vector Search', 'Next.js', 'OpenSearch', 'YOLO', 'Reinforcement Learning', 'QLoRA', 'LoRA', 'BM25', 'Learning to Rank', 'Haystack', 'BentoML', 'ASR', 'Kubeflow']

CAREER HISTORY:

---
Built a content recommendation system serving 10M+ users that combined collaborative filtering with content-based ranking. The system uses item-item similarity (via sentence-transformer embeddings) for cold starts and a gradient-boosted model trained on engagement signals for warm users. Most of my time went into the feature pipeline (~200 features) and the A/B testing infrastructure. The launch improved 7-day retention by 6% and time spent per session by 14%.

---
Implemented a RAG-based customer support chatbot integrated with our existing ticketing system. Built the document ingestion pipeline (chunking, embedding via OpenAI embeddings, storing in Pinecone) and the answer-generation layer (initially GPT-4, then a fine-tuned smaller model for cost control). Designed the evaluation framework with both automatic metrics (BLEU, ROUGE) and human-in-the-loop quality scores. Deployment cut average ticket resolution time by 31% for the supported categories.

---
Built and operated production ML pipelines using MLflow for experiment tracking, Kubeflow for orchestration, and our internal feature store. My main project was a churn prediction model that's now used by the customer success team to prioritize outreach. Designed the model monitoring stack: data drift detection, prediction distribution checks, and alerting. Mentored a junior engineer through their first end-to-end ML project last year.

---
Developed a semantic search feature for an internal knowledge base of ~500K documents. Used sentence-transformers (all-MiniLM-L6-v2 initially, later upgraded to bge-base) with FAISS for fast nearest-neighbor retrieval. Designed the query expansion module that handles vocabulary mismatch between user queries and document terms. Reported search-relevance improvement of 35% over the prior Elasticsearch BM25 setup, validated through human relevance judgments.

## Behaviour Score

In [40]:
import json
import pandas as pd

rows = []

with open(link, "r", encoding="utf-8") as f:

    for line in f:

        c = json.loads(line)

        signals = c["redrob_signals"]

        rows.append({

            "candidate_id":
                c["candidate_id"],

            "response_rate":
                signals["recruiter_response_rate"],

            "interview_completion":
                signals["interview_completion_rate"],

            "offer_acceptance":
                signals["offer_acceptance_rate"],

            "saved_by_recruiters":
                signals["saved_by_recruiters_30d"],

            "github_score":
                signals["github_activity_score"]
        })

behavior_df = pd.DataFrame(rows)

behavior_df.head()

,candidate_id,response_rate,interview_completion,offer_acceptance,saved_by_recruiters,github_score
0,CAND_0000001,0.34,0.71,0.58,4,9.2
1,CAND_0000002,0.29,0.62,-1.00,10,-1.0
2,CAND_0000003,0.46,0.86,-1.00,4,-1.0
3,CAND_0000004,0.26,0.35,-1.00,8,-1.0
4,CAND_0000005,0.37,0.74,-1.00,1,-1.0

In [41]:
behavior_df["offer_acceptance"] = (
    behavior_df["offer_acceptance"]
    .clip(lower=0)
)

In [42]:
print(
    behavior_df["offer_acceptance"].min()
)

0.0

In [43]:
behavior_df["behavior_score"] = (

      0.30 * behavior_df["response_rate"]

    + 0.30 * behavior_df["interview_completion"]

    + 0.20 * behavior_df["offer_acceptance"]

    + 0.10 * (
        behavior_df["saved_by_recruiters"]
        /
        behavior_df["saved_by_recruiters"].max()
      )

    + 0.10 * (
        behavior_df["github_score"]
        /
        behavior_df["github_score"].max()
      )
)

In [44]:
behavior_df["behavior_score"].describe()

count    100000.000000
mean          0.374713
std           0.105879
min           0.106468
25%           0.298718
50%           0.370718
75%           0.446218
max           0.821873
Name: behavior_score, dtype: float64

In [45]:
print(behavior_df.columns)

Index(['candidate_id', 'response_rate', 'interview_completion',
       'offer_acceptance', 'saved_by_recruiters', 'github_score',
       'behavior_score'],
      dtype='object')

In [46]:
final_df = production_df.merge(
    behavior_df[
        ["candidate_id", "behavior_score"]
    ],
    on="candidate_id"
)

print(final_df.shape)

(100000, 5)

In [47]:
final_df["final_score"] = (

      0.80 * final_df["production_score_norm"]

    + 0.20 * final_df["behavior_score"]

)

In [48]:
top100 = final_df.sort_values(
    "final_score",
    ascending=False
)

top100.head(50)

,candidate_id,title,production_score,production_score_norm,behavior_score,final_score
79386,CAND_0079387,AI Engineer,12,1.000000,0.706651,0.941330
55991,CAND_0055992,AI Engineer,11,0.916667,0.775639,0.888461
30952,CAND_0030953,Search Engineer,11,0.916667,0.620172,0.857368
44854,CAND_0044855,Senior Data Scientist,11,0.916667,0.542944,0.841922
44882,CAND_0044883,AI Engineer,10,0.833333,0.771505,0.820968
54122,CAND_0054123,Applied ML Engineer,10,0.833333,0.727537,0.812174
5648,CAND_0005649,Senior Data Scientist,10,0.833333,0.714782,0.809623
57562,CAND_0057563,NLP Engineer,10,0.833333,0.650779,0.796823
1609,CAND_0001610,Machine Learning Engineer,10,0.833333,0.644530,0.795573
81685,CAND_0081686,Search Engineer,10,0.833333,0.637634,0.794194
13612,CAND_0013613,Machine Learning Engineer,10,0.833333,0.624584,0.791583
26531,CAND_0026532,Recommendation Systems Engineer,10,0.833333,0.586040,0.783875
46063,CAND_0046064,Senior NLP Engineer,10,0.833333,0.574703,0.781607
75248,CAND_0075249,Applied ML Engineer,10,0.833333,0.570227,0.780712
96171,CAND_0096172,NLP Engineer,10,0.833333,0.543829,0.775433
60053,CAND_0060054,AI Engineer,10,0.833333,0.539718,0.774610
86150,CAND_0086151,Recommendation Systems Engineer,10,0.833333,0.528104,0.772287
30347,CAND_0030348,Machine Learning Engineer,10,0.833333,0.462468,0.759160
39753,CAND_0039754,Senior Applied Scientist,9,0.750000,0.790729,0.758146
66375,CAND_0066376,Applied ML Engineer,10,0.833333,0.456718,0.758010
28792,CAND_0028793,Search Engineer,9,0.750000,0.668509,0.733702
71973,CAND_0071974,Senior AI Engineer,9,0.750000,0.630949,0.726190
68810,CAND_0068811,Applied ML Engineer,9,0.750000,0.531839,0.706368
33860,CAND_0033861,Senior NLP Engineer,9,0.750000,0.499643,0.699929
41668,CAND_0041669,Recommendation Systems Engineer,8,0.666667,0.793418,0.692017
77336,CAND_0077337,Staff Machine Learning Engineer,8,0.666667,0.768175,0.686968
92277,CAND_0092278,Senior NLP Engineer,9,0.750000,0.385218,0.677044
91533,CAND_0091534,AI Engineer,8,0.666667,0.694361,0.672206
83306,CAND_0083307,Search Engineer,8,0.666667,0.667414,0.666816
8424,CAND_0008425,Senior NLP Engineer,8,0.666667,0.634755,0.660284
31592,CAND_0031593,Search Engineer,8,0.666667,0.622192,0.657772
58574,CAND_0058575,AI Engineer,8,0.666667,0.593767,0.652087
51291,CAND_0051292,Applied ML Engineer,8,0.666667,0.528924,0.639118
88024,CAND_0088025,Staff Machine Learning Engineer,7,0.583333,0.798737,0.626414
52681,CAND_0052682,NLP Engineer,7,0.583333,0.792716,0.625210
41567,CAND_0041568,Search Engineer,8,0.666667,0.445718,0.622477
40886,CAND_0040887,Machine Learning Engineer,7,0.583333,0.765794,0.619825
99400,CAND_0099401,NLP Engineer,8,0.666667,0.432371,0.619808
50875,CAND_0050876,Applied ML Engineer,7,0.583333,0.738604,0.614388
69904,CAND_0069905,Applied ML Engineer,7,0.583333,0.736483,0.613963
58687,CAND_0058688,AI Engineer,7,0.583333,0.735351,0.613737
10256,CAND_0010257,Senior Data Scientist,7,0.583333,0.730706,0.612808
11686,CAND_0011687,Senior NLP Engineer,7,0.583333,0.730491,0.612765
61654,CAND_0061655,Machine Learning Engineer,7,0.583333,0.703058,0.607278
2024,CAND_0002025,Senior AI Engineer,7,0.583333,0.702500,0.607167
12956,CAND_0012957,Search Engineer,7,0.583333,0.697712,0.606209
18498,CAND_0018499,Senior Machine Learning Engineer,7,0.583333,0.690833,0.604833
46524,CAND_0046525,Senior Machine Learning Engineer,7,0.583333,0.688374,0.604341
64903,CAND_0064904,AI Engineer,7,0.583333,0.686638,0.603994
75438,CAND_0075439,Machine Learning Engineer,7,0.583333,0.677921,0.602251

In [49]:

top_ids = top100["candidate_id"].head(10).tolist()

print(top_ids)

['CAND_0079387', 'CAND_0055992', 'CAND_0030953', 'CAND_0044855', 'CAND_0044883', 'CAND_0054123', 'CAND_0005649', 'CAND_0057563', 'CAND_0001610', 'CAND_0081686']

In [50]:
import json

with open(link, "r", encoding="utf-8") as f:

    for line in f:

        c = json.loads(line)

        if c["candidate_id"] in top_ids:

            print("="*100)
            print("ID:", c["candidate_id"])
            print("TITLE:", c["profile"]["current_title"])

            print("\nSUMMARY:")
            print(c["profile"]["summary"])

            print("\nSKILLS:")
            print([s["name"] for s in c["skills"][:10]])

            print()

====================================================================================================
ID: CAND_0001610
TITLE: Machine Learning Engineer

SUMMARY:
Machine learning engineer with 5.2 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I built our semantic search infrastructure from scratch — sentence-transformers, FAISS, the works. I've spent enough time debugging production ranking issues to know which signals matter and which are noise. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['Speech Recognition', 'Haystack', 'Deep Learning', 'Kubeflow', 'Pinecone', 'Salesforce CRM', 'Feature Engineering', 'scikit-learn', 'Fine-tuning LLMs', 'Data Science']

====================================================================================================
ID: CAND_0005649
TITLE: Senior Data Scientist

SUMMARY:
Machine learning engineer with 7.4 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I built our semantic search infrastructure from scratch — sentence-transformers, FAISS, the works. Along the way I've gotten comfortable with the operational side — A/B testing, drift monitoring, retraining schedules. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['Haystack', 'Redis', 'Prompt Engineering', 'Object Detection', 'Deep Learning', 'TensorFlow', 'Fine-tuning LLMs', 'Recommendation Systems', 'QLoRA', 'OpenCV']

====================================================================================================
ID: CAND_0030953
TITLE: Search Engineer

SUMMARY:
Machine learning engineer with 7.8 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I led the team that migrated our keyword-search-based product to embedding-based retrieval. Along the way I've gotten comfortable with the operational side — A/B testing, drift monitoring, retraining schedules. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['TTS', 'MLOps', 'Learning to Rank', 'Databricks', 'Time Series', 'ASR', 'Qdrant', 'Reinforcement Learning', 'Python', 'Hugging Face Transformers']

====================================================================================================
ID: CAND_0044855
TITLE: Senior Data Scientist

SUMMARY:
Machine learning engineer with 6.6 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, my main project for the last 18 months has been the recommendation system that powers our discovery feed. Along the way I've gotten comfortable with the operational side — A/B testing, drift monitoring, retraining schedules. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['Object Detection', 'Learning to Rank', 'Hugging Face Transformers', 'OpenSearch', 'BentoML', 'Information Retrieval', 'Pinecone', 'Machine Learning', 'Vector Search', 'NLP']

====================================================================================================
ID: CAND_0044883
TITLE: AI Engineer

SUMMARY:
Machine learning engineer with 6.3 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I've been the de-facto ML lead on a small team, shipping models across NLP and recsys. I've learned that most retrieval problems are actually evaluation problems in disguise. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['CNN', 'BM25', 'Computer Vision', 'Prompt Engineering', 'Embeddings', 'Data Science', 'QLoRA', 'ASR', 'Fine-tuning LLMs', 'TensorFlow']

====================================================================================================
ID: CAND_0054123
TITLE: Applied ML Engineer

SUMMARY:
Machine learning engineer with 4.7 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I've been the de-facto ML lead on a small team, shipping models across NLP and recsys. Along the way I've gotten comfortable with the operational side — A/B testing, drift monitoring, retraining schedules. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['LangChain', 'pgvector', 'Python', 'Weaviate', 'Qdrant', 'SEO', 'Vector Search', 'Hugging Face Transformers', 'Weights & Biases', 'Tailwind']

====================================================================================================
ID: CAND_0055992
TITLE: AI Engineer

SUMMARY:
Machine learning engineer with 6.8 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I led the team that migrated our keyword-search-based product to embedding-based retrieval. I care a lot about evaluation rigor — too many teams ship models without offline benchmarks they trust. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['Information Retrieval', 'MLflow', 'FAISS', 'RAG', 'Feature Engineering', 'Data Science', 'LangChain', 'SQL', 'OpenSearch', 'Embeddings']

====================================================================================================
ID: CAND_0057563
TITLE: NLP Engineer

SUMMARY:
Machine learning engineer with 6.8 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I built our semantic search infrastructure from scratch — sentence-transformers, FAISS, the works. I've learned that most retrieval problems are actually evaluation problems in disguise. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['Deep Learning', 'Speech Recognition', 'RAG', 'Rust', 'Elasticsearch', 'Feature Engineering', 'OpenSearch', 'SQL', 'QLoRA', 'Prompt Engineering']

====================================================================================================
ID: CAND_0079387
TITLE: AI Engineer

SUMMARY:
Machine learning engineer with 6.9 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I've been the de-facto ML lead on a small team, shipping models across NLP and recsys. I've learned that most retrieval problems are actually evaluation problems in disguise. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['scikit-learn', 'Recommendation Systems', 'Python', 'Time Series', 'Sentence Transformers', 'JavaScript', 'Illustrator', 'Vector Search', 'Next.js', 'OpenSearch']

====================================================================================================
ID: CAND_0081686
TITLE: Search Engineer

SUMMARY:
Machine learning engineer with 6.0 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, my main project for the last 18 months has been the recommendation system that powers our discovery feed. I've spent enough time debugging production ranking issues to know which signals matter and which are noise. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['Machine Learning', 'Kubeflow', 'Embeddings', 'FAISS', 'Feature Engineering', 'OpenCV', 'Milvus', 'BigQuery', 'CNN', 'Python']

In [51]:
top100 = final_df.sort_values(
    "final_score",
    ascending=False
).head(100)

In [52]:
top100["title"].value_counts()

title
Search Engineer                     13
Applied ML Engineer                 13
Machine Learning Engineer           13
AI Engineer                         12
Recommendation Systems Engineer     11
NLP Engineer                         8
Senior Data Scientist                8
Senior NLP Engineer                  6
Senior Machine Learning Engineer     5
Staff Machine Learning Engineer      4
Senior AI Engineer                   3
Senior Applied Scientist             2
Lead AI Engineer                     2
Name: count, dtype: int64

## JD requirement matching

In [53]:
jd_requirements = [
    "retrieval",
    "ranking",
    "recommendation",
    "search",
    "embeddings",
    "vector",
    "evaluation",
    "relevance",
    "rag",
    "pinecone",
    "weaviate",
    "qdrant",
    "milvus",
    "faiss",
    "opensearch",
    "elasticsearch",
    "ab testing",
    "ndcg",
    "mrr"
]

In [54]:
import json
import pandas as pd

jd_scores = []

with open(link, "r", encoding="utf-8") as f:

    for line in f:

        c = json.loads(line)

        career_text = " ".join(
            [
                job["description"]
                for job in c["career_history"]
            ]
        ).lower()

        score = 0

        for req in jd_requirements:

            if req in career_text:
                score += 1

        jd_scores.append({
            "candidate_id": c["candidate_id"],
            "jd_score": score
        })

jd_score_df = pd.DataFrame(jd_scores)

jd_score_df.head()

   candidate_id  jd_score
0  CAND_0000001         0
1  CAND_0000002         1
2  CAND_0000003         0
3  CAND_0000004         1
4  CAND_0000005         0

In [55]:
jd_score_df["jd_score_norm"] = (
    jd_score_df["jd_score"]
    /
    jd_score_df["jd_score"].max()
)

In [56]:
jd_score_df["jd_score_norm"].describe()

count    100000.000000
mean          0.044344
std           0.055463
min           0.000000
25%           0.000000
50%           0.000000
75%           0.083333
max           1.000000
Name: jd_score_norm, dtype: float64

In [57]:
final_df = final_df.merge(
    jd_score_df[
        ["candidate_id", "jd_score_norm"]
    ],
    on="candidate_id"
)

In [58]:
final_df.head()

,candidate_id,title,production_score,production_score_norm,behavior_score,final_score,jd_score_norm
0,CAND_0000001,Backend Engineer,0,0.000000,0.445494,0.089099,0.000000
1,CAND_0000002,Operations Manager,1,0.083333,0.284468,0.123560,0.083333
2,CAND_0000003,Customer Support,0,0.000000,0.399968,0.079994,0.000000
3,CAND_0000004,Marketing Manager,1,0.083333,0.191968,0.105060,0.083333
4,CAND_0000005,Accountant,0,0.000000,0.333218,0.066644,0.000000

In [59]:
final_df["final_score"] = (

      0.50 * final_df["production_score_norm"]

    + 0.30 * final_df["jd_score_norm"]

    + 0.20 * final_df["behavior_score"]

)

In [60]:
top100 = final_df.sort_values(
    "final_score",
    ascending=False
).head(100)

In [61]:
top100["title"].value_counts()

title
AI Engineer                         13
Search Engineer                     13
Applied ML Engineer                 12
Recommendation Systems Engineer     12
Senior Data Scientist               10
Machine Learning Engineer           10
NLP Engineer                         8
Senior NLP Engineer                  6
Senior Machine Learning Engineer     5
Staff Machine Learning Engineer      4
Senior AI Engineer                   3
Senior Applied Scientist             2
Lead AI Engineer                     2
Name: count, dtype: int64

In [62]:
top100[
    [
        "candidate_id",
        "title",
        "final_score"
    ]
].head(20)

       candidate_id                            title  final_score
79386  CAND_0079387                      AI Engineer     0.916330
55991  CAND_0055992                      AI Engineer     0.888461
30952  CAND_0030953                  Search Engineer     0.857368
44854  CAND_0044855            Senior Data Scientist     0.841922
39753  CAND_0039754         Senior Applied Scientist     0.833146
44882  CAND_0044883                      AI Engineer     0.820968
5648   CAND_0005649            Senior Data Scientist     0.809623
46063  CAND_0046064              Senior NLP Engineer     0.806607
54122  CAND_0054123              Applied ML Engineer     0.762174
28792  CAND_0028793                  Search Engineer     0.758702
57562  CAND_0057563                     NLP Engineer     0.746823
1609   CAND_0001610        Machine Learning Engineer     0.745573
81685  CAND_0081686                  Search Engineer     0.744194
13612  CAND_0013613        Machine Learning Engineer     0.741583
26531  CAND_0026532  Recommendation Systems Engineer     0.733875
75248  CAND_0075249              Applied ML Engineer     0.730712
96171  CAND_0096172                     NLP Engineer     0.725433
60053  CAND_0060054                      AI Engineer     0.724610
86150  CAND_0086151  Recommendation Systems Engineer     0.722287
91533  CAND_0091534                      AI Engineer     0.722206

In [63]:
top_ids = top100["candidate_id"].head(10).tolist()

In [64]:
import json

with open(link, "r", encoding="utf-8") as f:

    for line in f:

        c = json.loads(line)

        if c["candidate_id"] in top_ids:

            print("="*100)

            print("ID:", c["candidate_id"])
            print("TITLE:", c["profile"]["current_title"])

            print("\nSUMMARY:")
            print(c["profile"]["summary"])

            print("\nTOP SKILLS:")
            print([s["name"] for s in c["skills"][:10]])

            print("\nCAREER HISTORY:")

            for job in c["career_history"]:

                print("\n---")
                print(job["description"][:500])

====================================================================================================
ID: CAND_0005649
TITLE: Senior Data Scientist

SUMMARY:
Machine learning engineer with 7.4 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I built our semantic search infrastructure from scratch — sentence-transformers, FAISS, the works. Along the way I've gotten comfortable with the operational side — A/B testing, drift monitoring, retraining schedules. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

TOP SKILLS:
['Haystack', 'Redis', 'Prompt Engineering', 'Object Detection', 'Deep Learning', 'TensorFlow', 'Fine-tuning LLMs', 'Recommendation Systems', 'QLoRA', 'OpenCV']

CAREER HISTORY:

---
Developed a semantic search feature for an internal knowledge base of ~500K documents. Used sentence-transformers (all-MiniLM-L6-v2 initially, later upgraded to bge-base) with FAISS for fast nearest-neighbor retrieval. Designed the query expansion module that handles vocabulary mismatch between user queries and document terms. Reported search-relevance improvement of 35% over the prior Elasticsearch BM25 setup, validated through human relevance judgments.

---
Implemented a RAG-based customer support chatbot integrated with our existing ticketing system. Built the document ingestion pipeline (chunking, embedding via OpenAI embeddings, storing in Pinecone) and the answer-generation layer (initially GPT-4, then a fine-tuned smaller model for cost control). Designed the evaluation framework with both automatic metrics (BLEU, ROUGE) and human-in-the-loop quality scores. Deployment cut average ticket resolution time by 31% for the supported categories.

---
Built and operated production ML pipelines using MLflow for experiment tracking, Kubeflow for orchestration, and our internal feature store. My main project was a churn prediction model that's now used by the customer success team to prioritize outreach. Designed the model monitoring stack: data drift detection, prediction distribution checks, and alerting. Mentored a junior engineer through their first end-to-end ML project last year.

---
Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling it
====================================================================================================
ID: CAND_0028793
TITLE: Search Engineer

SUMMARY:
Machine learning engineer with 7.2 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I shipped our first RAG-based feature this year and now own the eval framework for it. I care a lot about evaluation rigor — too many teams ship models without offline benchmarks they trust. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

TOP SKILLS:
['SAP', 'Kubeflow', 'Embeddings', 'Haystack', 'YOLO', 'LoRA', 'PowerPoint', 'Learning to Rank', 'Information Retrieval', 'PEFT']

CAREER HISTORY:

---
Developed a semantic search feature for an internal knowledge base of ~500K documents. Used sentence-transformers (all-MiniLM-L6-v2 initially, later upgraded to bge-base) with FAISS for fast nearest-neighbor retrieval. Designed the query expansion module that handles vocabulary mismatch between user queries and document terms. Reported search-relevance improvement of 35% over the prior Elasticsearch BM25 setup, validated through human relevance judgments.

---
Implemented a RAG-based customer support chatbot integrated with our existing ticketing system. Built the document ingestion pipeline (chunking, embedding via OpenAI embeddings, storing in Pinecone) and the answer-generation layer (initially GPT-4, then a fine-tuned smaller model for cost control). Designed the evaluation framework with both automatic metrics (BLEU, ROUGE) and human-in-the-loop quality scores. Deployment cut average ticket resolution time by 31% for the supported categories.

---
Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling it
====================================================================================================
ID: CAND_0030953
TITLE: Search Engineer

SUMMARY:
Machine learning engineer with 7.8 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I led the team that migrated our keyword-search-based product to embedding-based retrieval. Along the way I've gotten comfortable with the operational side — A/B testing, drift monitoring, retraining schedules. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

TOP SKILLS:
['TTS', 'MLOps', 'Learning to Rank', 'Databricks', 'Time Series', 'ASR', 'Qdrant', 'Reinforcement Learning', 'Python', 'Hugging Face Transformers']

CAREER HISTORY:

---
Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling it

---
Built a content recommendation system serving 10M+ users that combined collaborative filtering with content-based ranking. The system uses item-item similarity (via sentence-transformer embeddings) for cold starts and a gradient-boosted model trained on engagement signals for warm users. Most of my time went into the feature pipeline (~200 features) and the A/B testing infrastructure. The launch improved 7-day retention by 6% and time spent per session by 14%.

---
Developed a semantic search feature for an internal knowledge base of ~500K documents. Used sentence-transformers (all-MiniLM-L6-v2 initially, later upgraded to bge-base) with FAISS for fast nearest-neighbor retrieval. Designed the query expansion module that handles vocabulary mismatch between user queries and document terms. Reported search-relevance improvement of 35% over the prior Elasticsearch BM25 setup, validated through human relevance judgments.

---
Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling it

---
Implemented a RAG-based customer support chatbot integrated with our existing ticketing system. Built the document ingestion pipeline (chunking, embedding via OpenAI embeddings, storing in Pinecone) and the answer-generation layer (initially GPT-4, then a fine-tuned smaller model for cost control). Designed the evaluation framework with both automatic metrics (BLEU, ROUGE) and human-in-the-loop quality scores. Deployment cut average ticket resolution time by 31% for the supported categories.
====================================================================================================
ID: CAND_0039754
TITLE: Senior Applied Scientist

SUMMARY:
Senior AI engineer with 8.3 years of hands-on experience building production ML systems, with a focus on search, retrieval, and ranking. Most recently, I rebuilt the candidate-JD matching pipeline from scratch, taking it from 0.72 to 0.91 NDCG@10, serving 50M+ queries per month. My day-to-day work spans embedding model selection and fine-tuning, hybrid retrieval architecture, learning-to-rank, behavioral-signal integration, and the offline/online evaluation that ties it all together. I've shipped systems in both early-stage product companies and at larger scale, and I've spent enough time on both that I know which tradeoffs apply where. I believe most ranking problems are solved by careful feature engineering and rigorous eval, not by bigger models. Currently exploring my next move — looking for senior IC or tech-lead roles where I can own the intelligence layer end-to-end.

TOP SKILLS:
['Fine-tuning LLMs', 'LlamaIndex', 'Qdrant', 'Reinforcement Learning', 'NLP', 'Statistical Modeling', 'Kubeflow', 'ASR', 'OpenSearch', 'Deep Learning']

CAREER HISTORY:

---
Owned the end-to-end ranking pipeline at a recommendations-heavy consumer product: candidate sourcing → embedding generation (using a fine-tuned BGE-large) → Pinecone retrieval → learning-to-rank re-scoring (XGBoost) → behavioral-signal integration. The hardest part wasn't the ML — it was the evaluation: building offline metrics that actually predicted what the recommendation would do to live engagement. After three iterations we landed on a calibration approach using simulated A/B tests that ha

---
Owned the design and rollout of a large-scale semantic search system serving an internal corpus of 35M+ items. Migrated the existing BM25-only retrieval to a hybrid setup combining sparse and dense vectors (sentence-transformers, MPNet-base initially, later fine-tuned BGE-large for our domain). The new system reduced p95 retrieval latency by 60% while improving NDCG@10 by 18% on our held-out eval set. Spent substantial time on the boring-but-critical parts: incremental index refresh, embedding d

---
Built a RAG-based ranking pipeline serving 50M+ queries per month for an internal recruiter-facing search product. The architecture combined BM25 + dense retrieval (BGE embeddings, FAISS HNSW) with an LLM-based re-ranker on the top-50, falling back to a learning-to-rank model when latency budget was tight. Designed the offline evaluation framework from scratch — NDCG, MRR, recall@K calibrated against online A/B engagement metrics. Drove the migration over 4 months including the recruiter-feedbac
====================================================================================================
ID: CAND_0044855
TITLE: Senior Data Scientist

SUMMARY:
Machine learning engineer with 6.6 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, my main project for the last 18 months has been the recommendation system that powers our discovery feed. Along the way I've gotten comfortable with the operational side — A/B testing, drift monitoring, retraining schedules. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

TOP SKILLS:
['Object Detection', 'Learning to Rank', 'Hugging Face Transformers', 'OpenSearch', 'BentoML', 'Information Retrieval', 'Pinecone', 'Machine Learning', 'Vector Search', 'NLP']

CAREER HISTORY:

---
Implemented a RAG-based customer support chatbot integrated with our existing ticketing system. Built the document ingestion pipeline (chunking, embedding via OpenAI embeddings, storing in Pinecone) and the answer-generation layer (initially GPT-4, then a fine-tuned smaller model for cost control). Designed the evaluation framework with both automatic metrics (BLEU, ROUGE) and human-in-the-loop quality scores. Deployment cut average ticket resolution time by 31% for the supported categories.

---
Built a content recommendation system serving 10M+ users that combined collaborative filtering with content-based ranking. The system uses item-item similarity (via sentence-transformer embeddings) for cold starts and a gradient-boosted model trained on engagement signals for warm users. Most of my time went into the feature pipeline (~200 features) and the A/B testing infrastructure. The launch improved 7-day retention by 6% and time spent per session by 14%.

---
Developed a semantic search feature for an internal knowledge base of ~500K documents. Used sentence-transformers (all-MiniLM-L6-v2 initially, later upgraded to bge-base) with FAISS for fast nearest-neighbor retrieval. Designed the query expansion module that handles vocabulary mismatch between user queries and document terms. Reported search-relevance improvement of 35% over the prior Elasticsearch BM25 setup, validated through human relevance judgments.
====================================================================================================
ID: CAND_0044883
TITLE: AI Engineer

SUMMARY:
Machine learning engineer with 6.3 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I've been the de-facto ML lead on a small team, shipping models across NLP and recsys. I've learned that most retrieval problems are actually evaluation problems in disguise. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

TOP SKILLS:
['CNN', 'BM25', 'Computer Vision', 'Prompt Engineering', 'Embeddings', 'Data Science', 'QLoRA', 'ASR', 'Fine-tuning LLMs', 'TensorFlow']

CAREER HISTORY:

---
Implemented a RAG-based customer support chatbot integrated with our existing ticketing system. Built the document ingestion pipeline (chunking, embedding via OpenAI embeddings, storing in Pinecone) and the answer-generation layer (initially GPT-4, then a fine-tuned smaller model for cost control). Designed the evaluation framework with both automatic metrics (BLEU, ROUGE) and human-in-the-loop quality scores. Deployment cut average ticket resolution time by 31% for the supported categories.

---
Built and operated production ML pipelines using MLflow for experiment tracking, Kubeflow for orchestration, and our internal feature store. My main project was a churn prediction model that's now used by the customer success team to prioritize outreach. Designed the model monitoring stack: data drift detection, prediction distribution checks, and alerting. Mentored a junior engineer through their first end-to-end ML project last year.

---
Developed a semantic search feature for an internal knowledge base of ~500K documents. Used sentence-transformers (all-MiniLM-L6-v2 initially, later upgraded to bge-base) with FAISS for fast nearest-neighbor retrieval. Designed the query expansion module that handles vocabulary mismatch between user queries and document terms. Reported search-relevance improvement of 35% over the prior Elasticsearch BM25 setup, validated through human relevance judgments.

---
Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling it
====================================================================================================
ID: CAND_0046064
TITLE: Senior NLP Engineer

SUMMARY:
Senior AI engineer with 8.9 years of hands-on experience building production ML systems, with a focus on search, retrieval, and ranking. Most recently, I rebuilt the candidate-JD matching pipeline from scratch, taking it from 0.72 to 0.91 NDCG@10, operating at single-digit-millisecond p95 retrieval latency. My day-to-day work spans embedding model selection and fine-tuning, hybrid retrieval architecture, learning-to-rank, behavioral-signal integration, and the offline/online evaluation that ties it all together. I've shipped systems in both early-stage product companies and at larger scale, and I've spent enough time on both that I know which tradeoffs apply where. I believe most ranking problems are solved by careful feature engineering and rigorous eval, not by bigger models. Currently exploring my next move — looking for senior IC or tech-lead roles where I can own the intelligence layer end-to-end.

TOP SKILLS:
['Python', 'Image Classification', 'OpenCV', 'Pinecone', 'Haystack', 'Six Sigma', 'TTS', 'Diffusion Models', 'BM25', 'YOLO']

CAREER HISTORY:

---
Fine-tuned LLaMA-2-7B and Mistral-7B variants using LoRA and QLoRA for domain-specific candidate-JD matching. Built the data curation pipeline that generated 200K high-quality preference pairs from recruiter labels, plus the eval harness using both ranking metrics and human-quality scores. Deployed the model via BentoML on Kubernetes with sub-200ms p95 latency by quantizing to INT8 and batching at the request level. Cost per inference dropped from $0.04 with GPT-3.5-fallback to under $0.001.

---
Built a RAG-based ranking pipeline serving 50M+ queries per month for an internal recruiter-facing search product. The architecture combined BM25 + dense retrieval (BGE embeddings, FAISS HNSW) with an LLM-based re-ranker on the top-50, falling back to a learning-to-rank model when latency budget was tight. Designed the offline evaluation framework from scratch — NDCG, MRR, recall@K calibrated against online A/B engagement metrics. Drove the migration over 4 months including the recruiter-feedbac

---

In [65]:
top100.head(20)

,candidate_id,title,production_score,production_score_norm,behavior_score,final_score,jd_score_norm
79386,CAND_0079387,AI Engineer,12,1.000000,0.706651,0.916330,0.916667
55991,CAND_0055992,AI Engineer,11,0.916667,0.775639,0.888461,0.916667
30952,CAND_0030953,Search Engineer,11,0.916667,0.620172,0.857368,0.916667
44854,CAND_0044855,Senior Data Scientist,11,0.916667,0.542944,0.841922,0.916667
39753,CAND_0039754,Senior Applied Scientist,9,0.750000,0.790729,0.833146,1.000000
44882,CAND_0044883,AI Engineer,10,0.833333,0.771505,0.820968,0.833333
5648,CAND_0005649,Senior Data Scientist,10,0.833333,0.714782,0.809623,0.833333
46063,CAND_0046064,Senior NLP Engineer,10,0.833333,0.574703,0.806607,0.916667
54122,CAND_0054123,Applied ML Engineer,10,0.833333,0.727537,0.762174,0.666667
28792,CAND_0028793,Search Engineer,9,0.750000,0.668509,0.758702,0.833333
57562,CAND_0057563,NLP Engineer,10,0.833333,0.650779,0.746823,0.666667
1609,CAND_0001610,Machine Learning Engineer,10,0.833333,0.644530,0.745573,0.666667
81685,CAND_0081686,Search Engineer,10,0.833333,0.637634,0.744194,0.666667
13612,CAND_0013613,Machine Learning Engineer,10,0.833333,0.624584,0.741583,0.666667
26531,CAND_0026532,Recommendation Systems Engineer,10,0.833333,0.586040,0.733875,0.666667
75248,CAND_0075249,Applied ML Engineer,10,0.833333,0.570227,0.730712,0.666667
96171,CAND_0096172,NLP Engineer,10,0.833333,0.543829,0.725433,0.666667
60053,CAND_0060054,AI Engineer,10,0.833333,0.539718,0.724610,0.666667
86150,CAND_0086151,Recommendation Systems Engineer,10,0.833333,0.528104,0.722287,0.666667
91533,CAND_0091534,AI Engineer,8,0.666667,0.694361,0.722206,0.833333

In [66]:
candidate_embeddings.shape
# (100000, 384)

(100, 384)

## Convert all 100000 into vectors

In [67]:
candidate_embeddings = model.encode(
    candidate_text_df["candidate_text"].tolist(),
    batch_size=128,
    normalize_embeddings=True,
    show_progress_bar=True
)

Batches:   0%|          | 0/782 [00:00<?, ?it/s]

In [68]:
import numpy as np

np.save("candidate_embeddings.npy", candidate_embeddings)

In [69]:
import numpy as np

candidate_embeddings = np.load(
    "candidate_embeddings.npy"
)

In [70]:
candidate_embeddings.shape
# (100000, 384)

(100000, 384)

In [71]:
from docx import Document

doc = Document("/content/drive/MyDrive/[PUB] India_runs_data_and_ai_challenge/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/job_description.docx")

jd_text = "\n".join(
    p.text for p in doc.paragraphs
)

print(jd_text[:2000])

Job Description: Senior AI Engineer — Founding Team
Company: Redrob AI (Series A AI-native talent intelligence platform)
Location: Pune/Noida, India (Hybrid — flexible cadence) | Open to relocation candidates from Tier-1 Indian cities
Employment Type: Full-time
Experience Required: 5–9 years (see "what we mean by this" below)

Let's be honest about this role
We're going to write this JD differently from most. We're a Series A company that just raised our round and we're building a new AI Engineering org from scratch. This is the kind of role where the JD changes every six months because the company changes every six months. So instead of pretending we have a fixed checklist, we're going to tell you what we actually need and what we've gotten wrong before.
If you've spent your career at Google or Meta and you want a well-scoped role with a defined ladder, this isn't it.
If you've spent your career bouncing between early-stage startups and you want to "just code" without having to think about product or recruiter workflows or eval frameworks, this also isn't it.
We need someone who is simultaneously comfortable with two things that sound contradictory:
Deep technical depth in modern ML systems — embeddings, retrieval, ranking, LLMs, fine-tuning.
Scrappy product-engineering attitude — willing to ship a working ranker in a week even if the underlying ML is "obviously suboptimal," because we need to learn from real users before we know what to actually optimize for.
These are not contradictory in real life. They feel contradictory because of how engineering culture sorted itself into "researcher" vs "shipper" archetypes. We need both modes available in the same person, and we'd rather you tilt slightly toward shipper than toward researcher.

What you'd actually be doing
The high-level mandate: own the intelligence layer of Redrob's product. That means the ranking, retrieval, and matching systems that decide what recruiters see when they search for candidates and what can

In [72]:
print(len(jd_text))

9572

In [73]:
jd_embedding = model.encode(
    jd_text,
    normalize_embeddings=True
)

In [74]:
from sentence_transformers import util

semantic_scores = util.cos_sim(
    jd_embedding,
    candidate_embeddings
)[0].cpu().numpy()

In [75]:
semantic_df = pd.DataFrame({
    "candidate_id": candidate_text_df["candidate_id"],
    "semantic_score": semantic_scores
})

In [76]:
semantic_df.head()

   candidate_id  semantic_score
0  CAND_0000001        0.435110
1  CAND_0000002        0.593928
2  CAND_0000003        0.515823
3  CAND_0000004        0.502864
4  CAND_0000005        0.444998

In [77]:
semantic_top20 = (
    semantic_df
    .sort_values(
        "semantic_score",
        ascending=False
    )
    .head(20)
)

semantic_top20 = semantic_top20.merge(
    final_df[
        ["candidate_id", "title"]
    ],
    on="candidate_id"
)

semantic_top20

    candidate_id  semantic_score                title
0   CAND_0050679        0.671434       Civil Engineer
1   CAND_0020974        0.660944       Civil Engineer
2   CAND_0077776        0.657228       Civil Engineer
3   CAND_0020806        0.657144       Civil Engineer
4   CAND_0035214        0.656973  Mechanical Engineer
5   CAND_0084718        0.655979           HR Manager
6   CAND_0092767        0.653874  Mechanical Engineer
7   CAND_0037081        0.652834       Civil Engineer
8   CAND_0023896        0.652591   Operations Manager
9   CAND_0064215        0.651841       Civil Engineer
10  CAND_0053064        0.651089       Civil Engineer
11  CAND_0030386        0.650348       Civil Engineer
12  CAND_0013264        0.649960       Civil Engineer
13  CAND_0040259        0.649820           HR Manager
14  CAND_0071908        0.648975       Civil Engineer
15  CAND_0097246        0.647896           HR Manager
16  CAND_0098356        0.647364       Civil Engineer
17  CAND_0053774        0.647320       Civil Engineer
18  CAND_0092796        0.647191  Mechanical Engineer
19  CAND_0093684        0.646951       Civil Engineer

In [78]:
top_ids = semantic_top20["candidate_id"].head(10).tolist()

with open(link, "r", encoding="utf-8") as f:

    for line in f:

        c = json.loads(line)

        if c["candidate_id"] in top_ids:

            print("="*100)
            print(c["candidate_id"])
            print("TITLE:", c["profile"]["current_title"])
            print("HEADLINE:", c["profile"]["headline"])

            print("\nSKILLS:")
            print([s["name"] for s in c["skills"][:15]])

            print("\nSUMMARY:")
            print(c["profile"]["summary"][:500])

            print()

====================================================================================================
CAND_0020806
TITLE: Civil Engineer
HEADLINE: Civil Engineer | Generative AI explorer

SKILLS:
['Apache Flink', 'Docker', 'Figma', 'Illustrator', 'TypeScript', 'Hadoop', 'GCP', 'PostgreSQL', 'Databricks', 'GraphQL', 'Embeddings', 'Fine-tuning LLMs', 'Vector Search', 'Prompt Engineering', 'Pinecone']

SUMMARY:
Civil Engineer with 14.1+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can augment my work. I've been taking online courses on RAG and vector databases, experimenting with LangChain and the OpenAI API for side projects, and exploring how LLMs can streamline workflows in my cu

====================================================================================================
CAND_0020974
TITLE: Civil Engineer
HEADLINE: Civil Engineer | Exploring AI & GenAI applications

SKILLS:
['Vue.js', 'Databricks', 'Accounting', 'HTML', 'Java', 'PostgreSQL', 'Vector Search', 'Prompt Engineering', 'LLMs', 'Fine-tuning LLMs', 'Embeddings', 'LangChain', 'Sentence Transformers', 'Semantic Search', 'Hugging Face Transformers']

SUMMARY:
Civil Engineer with 1.1+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can augment my work. I've been taking online courses on RAG and vector databases, experimenting with LangChain and the OpenAI API for side projects, and exploring how LLMs can streamline workflows in my cur

====================================================================================================
CAND_0023896
TITLE: Operations Manager
HEADLINE: Operations Manager | Exploring AI & GenAI applications

SKILLS:
['Redis', 'Kafka', 'Reinforcement Learning', 'SEO', 'Project Management', 'Hadoop', 'Vue.js', 'Excel', 'Recommendation Systems', 'Embeddings', 'Pinecone', 'FAISS', 'Fine-tuning LLMs', 'Information Retrieval', 'RAG']

SUMMARY:
Operations Manager with 13.4+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can augment my work. I've been taking online courses on RAG and vector databases, experimenting with LangChain and the OpenAI API for side projects, and exploring how LLMs can streamline workflows in m

====================================================================================================
CAND_0035214
TITLE: Mechanical Engineer
HEADLINE: Mechanical Engineer | Exploring AI & GenAI applications

SKILLS:
['SEO', 'Salesforce CRM', 'SAP', 'PostgreSQL', 'Data Science', 'SQL', 'React', 'Embeddings', 'Recommendation Systems', 'RAG', 'LLMs', 'Fine-tuning LLMs', 'Semantic Search', 'Pinecone', 'FAISS']

SUMMARY:
Mechanical Engineer with 5.3+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can augment my work. I've been taking online courses on RAG and vector databases, experimenting with LangChain and the OpenAI API for side projects, and exploring how LLMs can streamline workflows in m

====================================================================================================
CAND_0037081
TITLE: Civil Engineer
HEADLINE: Civil Engineer | Generative AI explorer

SKILLS:
['SQL', 'FastAPI', 'HTML', 'Illustrator', 'PostgreSQL', 'GCP', 'Kafka', 'Scrum', 'Node.js', 'Semantic Search', 'LLMs', 'FAISS', 'RAG', 'Information Retrieval', 'Fine-tuning LLMs']

SUMMARY:
Civil Engineer with 12.6+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can augment my work. I've been taking online courses on RAG and vector databases, experimenting with LangChain and the OpenAI API for side projects, and exploring how LLMs can streamline workflows in my cu

====================================================================================================
CAND_0050679
TITLE: Civil Engineer
HEADLINE: Civil Engineer | Exploring AI & GenAI applications

SKILLS:
['Hadoop', 'Flask', 'TypeScript', 'Apache Flink', 'SAP', 'Six Sigma', 'JavaScript', 'ASR', 'Content Writing', 'Marketing', 'Snowflake', 'RAG', 'Prompt Engineering', 'Sentence Transformers', 'Recommendation Systems']

SUMMARY:
Civil Engineer with 2.3+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can augment my work. I've been taking online courses on RAG and vector databases, experimenting with LangChain and the OpenAI API for side projects, and exploring how LLMs can streamline workflows in my cur

====================================================================================================
CAND_0064215
TITLE: Civil Engineer
HEADLINE: Civil Engineer | Generative AI explorer

SKILLS:
['Accounting', 'Node.js', 'Hadoop', 'Salesforce CRM', 'CI/CD', 'Redux', 'Spark', 'Data Science', 'BigQuery', 'Docker', 'SQL', 'LLMs', 'Prompt Engineering', 'LangChain', 'Vector Search']

SUMMARY:
Civil Engineer with 8.7+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can augment my work. I've been taking online courses on RAG and vector databases, experimenting with LangChain and the OpenAI API for side projects, and exploring how LLMs can streamline workflows in my cur

====================================================================================================
CAND_0077776
TITLE: Civil Engineer
HEADLINE: Civil Engineer | Exploring AI & GenAI applications

SKILLS:
['Salesforce CRM', 'YOLO', 'Webpack', 'Airflow', 'CSS', 'Redux', 'Hadoop', 'Information Retrieval', 'Fine-tuning LLMs', 'FAISS', 'Vector Search', 'Embeddings', 'Pinecone', 'Hugging Face Transformers', 'Sentence Transformers']

SUMMARY:
Civil Engineer with 5.3+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can augment my work. I've been taking online courses on RAG and vector databases, experimenting with LangChain and the OpenAI API for side projects, and exploring how LLMs can streamline workflows in my cur

====================================================================================================
CAND_0084718
TITLE: HR Manager
HEADLINE: HR Manager | Exploring AI & GenAI applications

SKILLS:
['Redis', 'Feature Engineering', 'Tailwind', 'Apache Flink', 'Airflow', 'Hadoop', 'dbt', 'Six Sigma', 'SAP', 'FastAPI', 'Information Retrieval', 'Vector Search', 'LangChain', 'Hugging Face Transformers', 'Embeddings']

SUMMARY:
HR Manager with 4.9+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can augment my work. I've been taking online courses on RAG and vector databases, experimenting with LangChain and the OpenAI API for side projects, and exploring how LLMs can streamline workflows in my current

====================================================================================================
CAND_0092767
TITLE: Mechanical Engineer
HEADLINE: Mechanical Engineer | Generative AI explorer

SKILLS:
['GCP', 'SEO', 'Redux', 'Kubernetes', 'CI/CD', 'Tally', 'PostgreSQL', 'FAISS', 'Sentence Transformers', 'Fine-tuning LLMs', 'Prompt Engineering', 'Embeddings', 'LLMs', 'LangChain', 'Semantic Search']

SUMMARY:
Mechanical Engineer with 9.0+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can augment my work. I've been taking online courses on RAG and vector databases, experimenting with LangChain and the OpenAI API for side projects, and exploring how LLMs can streamline workflows in m

In [79]:
production_keywords = [
    "built",
    "deployed",
    "production",
    "pipeline",
    "retrieval",
    "ranking",
    "recommendation",
    "rag",
    "vector search",
    "embeddings",
    "fine-tuning",
    "evaluation",
    "ndcg",
    "mrr",
    "ab testing",
    "monitoring",
    "mlflow",
    "kubeflow",
    "pinecone",
    "faiss",
    "qdrant",
    "weaviate",
    "opensearch"
]

In [80]:
def calculate_production_score(text):

    text = str(text).lower()

    score = 0

    for keyword in production_keywords:

        if keyword in text:
            score += 1

    return score

In [81]:
candidate_text_df["production_evidence"] = (
    candidate_text_df["candidate_text"]
    .apply(calculate_production_score)
)

In [82]:
candidate_text_df["production_evidence"].describe()

count    100000.000000
mean          2.941360
std           1.872585
min           0.000000
25%           2.000000
50%           2.000000
75%           4.000000
max          19.000000
Name: production_evidence, dtype: float64

In [83]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

candidate_text_df["production_evidence_norm"] = scaler.fit_transform(
    candidate_text_df[["production_evidence"]]
)

In [84]:
candidate_text_df["production_evidence_norm"].describe()

count    100000.000000
mean          0.154808
std           0.098557
min           0.000000
25%           0.105263
50%           0.105263
75%           0.210526
max           1.000000
Name: production_evidence_norm, dtype: float64

In [85]:
final_df = final_df.merge(
    candidate_text_df[
        ["candidate_id", "production_evidence_norm"]
    ],
    on="candidate_id",
    how="left"
)

In [86]:
final_df[
    [
        "candidate_id",
        "production_evidence_norm"
    ]
].head()

   candidate_id  production_evidence_norm
0  CAND_0000001                  0.210526
1  CAND_0000002                  0.105263
2  CAND_0000003                  0.000000
3  CAND_0000004                  0.105263
4  CAND_0000005                  0.052632

In [87]:
final_df.columns

Index(['candidate_id', 'title', 'production_score', 'production_score_norm',
       'behavior_score', 'final_score', 'jd_score_norm',
       'production_evidence_norm'],
      dtype='object')

In [88]:
semantic_df.head()

   candidate_id  semantic_score
0  CAND_0000001        0.435110
1  CAND_0000002        0.593928
2  CAND_0000003        0.515823
3  CAND_0000004        0.502864
4  CAND_0000005        0.444998

In [89]:
final_df = final_df.merge(
    semantic_df,
    on="candidate_id",
    how="left"
)

In [90]:
final_df.columns

Index(['candidate_id', 'title', 'production_score', 'production_score_norm',
       'behavior_score', 'final_score', 'jd_score_norm',
       'production_evidence_norm', 'semantic_score'],
      dtype='object')

In [91]:
final_df["final_score_v2"] = (
      0.50 * final_df["semantic_score"]
    + 0.30 * final_df["behavior_score"]
    + 0.20 * final_df["production_evidence_norm"]
)

In [92]:
top20_v2 = (
    final_df
    .sort_values(
        "final_score_v2",
        ascending=False
    )
    .head(20)
)

top20_v2[
    [
        "candidate_id",
        "title",
        "semantic_score",
        "behavior_score",
        "production_evidence_norm",
        "final_score_v2"
    ]
]

,candidate_id,title,semantic_score,behavior_score,production_evidence_norm,final_score_v2
39753,CAND_0039754,Senior Applied Scientist,0.603239,0.790729,1.000000,0.738838
11686,CAND_0011687,Senior NLP Engineer,0.575021,0.730491,0.842105,0.675079
77336,CAND_0077337,Staff Machine Learning Engineer,0.590700,0.768175,0.736842,0.673171
44882,CAND_0044883,AI Engineer,0.562733,0.771505,0.789474,0.670713
55991,CAND_0055992,AI Engineer,0.579351,0.775639,0.736842,0.669735
2024,CAND_0002025,Senior AI Engineer,0.612076,0.702500,0.736842,0.664156
55904,CAND_0055905,Senior Machine Learning Engineer,0.593365,0.663218,0.842105,0.664069
5259,CAND_0005260,Senior NLP Engineer,0.578742,0.675718,0.842105,0.660508
74734,CAND_0074735,Applied ML Engineer,0.543409,0.754256,0.789474,0.655876
86021,CAND_0086022,Senior Applied Scientist,0.580495,0.618856,0.894737,0.654852
18498,CAND_0018499,Senior Machine Learning Engineer,0.557288,0.690833,0.842105,0.654315
53590,CAND_0053591,AI Engineer,0.563074,0.786225,0.684211,0.654246
5648,CAND_0005649,Senior Data Scientist,0.535754,0.714782,0.842105,0.650733
81845,CAND_0081846,Lead AI Engineer,0.594343,0.613278,0.842105,0.649576
93546,CAND_0093547,Senior Machine Learning Engineer,0.585592,0.648654,0.789474,0.645287
46524,CAND_0046525,Senior Machine Learning Engineer,0.595146,0.688374,0.684211,0.640927
46063,CAND_0046064,Senior NLP Engineer,0.576020,0.574703,0.894737,0.639368
83306,CAND_0083307,Search Engineer,0.560539,0.667414,0.789474,0.638388
91533,CAND_0091534,AI Engineer,0.563998,0.694361,0.736842,0.637676
33860,CAND_0033861,Senior NLP Engineer,0.596078,0.499643,0.947368,0.637406

In [93]:
top_ids = top20_v2["candidate_id"].head(5).tolist()

with open(link, "r", encoding="utf-8") as f:

    for line in f:

        c = json.loads(line)

        if c["candidate_id"] in top_ids:

            print("="*100)
            print("ID:", c["candidate_id"])
            print("TITLE:", c["profile"]["current_title"])

            print("\nSUMMARY:")
            print(c["profile"]["summary"])

            print("\nSKILLS:")
            print([s["name"] for s in c["skills"][:20]])
            print()

====================================================================================================
ID: CAND_0011687
TITLE: Senior NLP Engineer

SUMMARY:
Senior AI engineer with 7.8 years of hands-on experience building production ML systems, with a focus on search, retrieval, and ranking. Most recently, I owned the offline-online evaluation harness — NDCG/MRR/recall calibrated to live A/B metrics, with an index footprint of ~600GB and incremental refresh every 15 min. My day-to-day work spans embedding model selection and fine-tuning, hybrid retrieval architecture, learning-to-rank, behavioral-signal integration, and the offline/online evaluation that ties it all together. I've shipped systems in both early-stage product companies and at larger scale, and I've spent enough time on both that I know which tradeoffs apply where. I believe most ranking problems are solved by careful feature engineering and rigorous eval, not by bigger models. Currently exploring my next move — looking for senior IC or tech-lead roles where I can own the intelligence layer end-to-end.

SKILLS:
['TensorFlow', 'OpenSearch', 'FAISS', 'PEFT', 'Feature Engineering', 'Embeddings', 'LangChain', 'MLOps', 'Weaviate', 'PyTorch', 'Image Classification', 'Semantic Search', 'LlamaIndex']

====================================================================================================
ID: CAND_0039754
TITLE: Senior Applied Scientist

SUMMARY:
Senior AI engineer with 8.3 years of hands-on experience building production ML systems, with a focus on search, retrieval, and ranking. Most recently, I rebuilt the candidate-JD matching pipeline from scratch, taking it from 0.72 to 0.91 NDCG@10, serving 50M+ queries per month. My day-to-day work spans embedding model selection and fine-tuning, hybrid retrieval architecture, learning-to-rank, behavioral-signal integration, and the offline/online evaluation that ties it all together. I've shipped systems in both early-stage product companies and at larger scale, and I've spent enough time on both that I know which tradeoffs apply where. I believe most ranking problems are solved by careful feature engineering and rigorous eval, not by bigger models. Currently exploring my next move — looking for senior IC or tech-lead roles where I can own the intelligence layer end-to-end.

SKILLS:
['Fine-tuning LLMs', 'LlamaIndex', 'Qdrant', 'Reinforcement Learning', 'NLP', 'Statistical Modeling', 'Kubeflow', 'ASR', 'OpenSearch', 'Deep Learning', 'Machine Learning', 'LLMs', 'BM25', 'Weaviate', 'Python', 'TensorFlow', 'CI/CD', 'pgvector', 'Speech Recognition', 'Elasticsearch']

====================================================================================================
ID: CAND_0044883
TITLE: AI Engineer

SUMMARY:
Machine learning engineer with 6.3 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I've been the de-facto ML lead on a small team, shipping models across NLP and recsys. I've learned that most retrieval problems are actually evaluation problems in disguise. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['CNN', 'BM25', 'Computer Vision', 'Prompt Engineering', 'Embeddings', 'Data Science', 'QLoRA', 'ASR', 'Fine-tuning LLMs', 'TensorFlow', 'Deep Learning', 'scikit-learn', 'Object Detection', 'PyTorch', 'Semantic Search']

====================================================================================================
ID: CAND_0055992
TITLE: AI Engineer

SUMMARY:
Machine learning engineer with 6.8 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I led the team that migrated our keyword-search-based product to embedding-based retrieval. I care a lot about evaluation rigor — too many teams ship models without offline benchmarks they trust. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['Information Retrieval', 'MLflow', 'FAISS', 'RAG', 'Feature Engineering', 'Data Science', 'LangChain', 'SQL', 'OpenSearch', 'Embeddings', 'Prompt Engineering', 'Accounting', 'Vue.js', 'Fine-tuning LLMs', 'Milvus', 'Deep Learning']

====================================================================================================
ID: CAND_0077337
TITLE: Staff Machine Learning Engineer

SUMMARY:
Senior AI engineer with 7.0 years of hands-on experience building production ML systems, with a focus on search, retrieval, and ranking. Most recently, I designed the company's first hybrid retrieval system combining BM25 with dense vector recall, serving 50M+ queries per month. My day-to-day work spans embedding model selection and fine-tuning, hybrid retrieval architecture, learning-to-rank, behavioral-signal integration, and the offline/online evaluation that ties it all together. I've shipped systems in both early-stage product companies and at larger scale, and I've spent enough time on both that I know which tradeoffs apply where. I care more about shipping a working system in 6 weeks than a theoretically perfect one in 6 months. Currently exploring my next move — looking for senior IC or tech-lead roles where I can own the intelligence layer end-to-end.

SKILLS:
['GANs', 'Semantic Search', 'QLoRA', 'pgvector', 'Pinecone', 'Feature Engineering', 'BM25', 'Information Retrieval', 'LLMs', 'OpenCV', 'Data Science', 'Forecasting', 'Excel', 'RAG', 'Qdrant', 'Recommendation Systems', 'Sentence Transformers', 'LlamaIndex', 'Python', 'OpenSearch']

In [94]:
top100_v2 = (
    final_df
    .sort_values(
        "final_score_v2",
        ascending=False
    )
    .head(100)
)

In [95]:
top100_v2["title"].value_counts()

title
Applied ML Engineer                 13
AI Engineer                         11
Senior Data Scientist                8
Search Engineer                      7
Recommendation Systems Engineer      6
Staff Machine Learning Engineer      5
Senior Machine Learning Engineer     5
Senior NLP Engineer                  5
Machine Learning Engineer            5
HR Manager                           5
Civil Engineer                       4
Senior Software Engineer (ML)        4
NLP Engineer                         4
Senior AI Engineer                   3
Senior Applied Scientist             2
Lead AI Engineer                     2
AI Specialist                        2
Project Manager                      2
Business Analyst                     2
Junior ML Engineer                   1
Operations Manager                   1
Graphic Designer                     1
AI Research Engineer                 1
Mechanical Engineer                  1
Name: count, dtype: int64

In [96]:
top100_v2[
    top100_v2["title"].isin(
        ["HR Manager", "Civil Engineer"]
    )
][
    [
        "candidate_id",
        "title",
        "semantic_score",
        "behavior_score",
        "production_evidence_norm",
        "final_score_v2"
    ]
].head(20)

,candidate_id,title,semantic_score,behavior_score,production_evidence_norm,final_score_v2
60219,CAND_0060220,HR Manager,0.645850,0.603718,0.473684,0.598777
66944,CAND_0066945,HR Manager,0.611184,0.644547,0.473684,0.593693
81471,CAND_0081472,Civil Engineer,0.638341,0.631913,0.421053,0.592955
77775,CAND_0077776,Civil Engineer,0.657228,0.564714,0.473684,0.592765
96942,CAND_0096943,HR Manager,0.629512,0.530052,0.578947,0.589561
31353,CAND_0031354,HR Manager,0.642075,0.504503,0.578947,0.588178
69888,CAND_0069889,Civil Engineer,0.624307,0.623452,0.421053,0.583400
39981,CAND_0039982,HR Manager,0.596217,0.557550,0.578947,0.581163
20805,CAND_0020806,Civil Engineer,0.657144,0.473468,0.526316,0.575875

In [97]:
cand_id = "CAND_0060220"

In [98]:
cand_id = "CAND_0060220"

with open(link, "r", encoding="utf-8") as f:

    for line in f:

        c = json.loads(line)

        if c["candidate_id"] == cand_id:

            print("="*100)
            print("ID:", c["candidate_id"])
            print("TITLE:", c["profile"]["current_title"])
            print("HEADLINE:", c["profile"]["headline"])

            print("\nSUMMARY:")
            print(c["profile"]["summary"])

            print("\nSKILLS:")
            print([s["name"] for s in c["skills"][:20]])

            break

====================================================================================================
ID: CAND_0060220
TITLE: HR Manager
HEADLINE: HR Manager | Generative AI explorer

SUMMARY:
HR Manager with 1.6+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can augment my work. I've been taking online courses on RAG and vector databases, experimenting with LangChain and the OpenAI API for side projects, and exploring how LLMs can streamline workflows in my current function. Open to roles that combine my existing domain experience with emerging AI technologies — I think the most interesting opportunities are at this intersection. Looking for positions where I can contribute both my functional expertise and grow my AI capabilities.

SKILLS:
['Snowflake', 'Redis', 'Apache Beam', 'Next.js', 'JavaScript', 'AWS', 'Information Retrieval', 'Semantic Search', 'LLMs', 'Hugging Face Transformers', 'Fine-tuning LLMs', 'Recommendation Systems', 'Prompt Engineering', 'Embeddings', 'LangChain', 'RAG', 'FAISS', 'Pinecone']

In [99]:
positive_phrases = [
    "built",
    "deployed",
    "production",
    "owned",
    "shipped",
    "serving",
    "queries",
    "users",
    "ndcg",
    "mrr",
    "ranking",
    "retrieval",
    "evaluation",
    "a/b",
    "ab testing",
    "monitoring",
    "mlflow",
    "kubeflow",
    "learning-to-rank"
]

In [100]:
negative_phrases = [
    "online courses",
    "experimenting with",
    "side projects",
    "exploring ai",
    "generative ai explorer",
    "grow my ai capabilities",
    "excited about ai"
]

In [101]:
def professional_score(text):

    text = str(text).lower()

    positive = 0
    negative = 0

    for phrase in positive_phrases:
        if phrase in text:
            positive += 1

    for phrase in negative_phrases:
        if phrase in text:
            negative += 1

    return positive - negative

In [102]:
candidate_text_df["professional_score"] = (
    candidate_text_df["candidate_text"]
    .apply(professional_score)
)

In [103]:
candidate_text_df["professional_score"].describe()

count    100000.000000
mean          2.206210
std           1.465029
min          -4.000000
25%           1.000000
50%           3.000000
75%           3.000000
max          15.000000
Name: professional_score, dtype: float64

In [104]:
candidate_text_df[
    ["candidate_id", "professional_score"]
].sort_values(
    "professional_score",
    ascending=False
).head(20)

       candidate_id  professional_score
5259   CAND_0005260                  15
39753  CAND_0039754                  15
33860  CAND_0033861                  15
55904  CAND_0055905                  15
41610  CAND_0041611                  14
86021  CAND_0086022                  14
46063  CAND_0046064                  14
77336  CAND_0077337                  14
92277  CAND_0092278                  14
81845  CAND_0081846                  14
8424   CAND_0008425                  13
18498  CAND_0018499                  13
68810  CAND_0068811                  13
99400  CAND_0099401                  13
10256  CAND_0010257                  13
93546  CAND_0093547                  12
22811  CAND_0022812                  12
7410   CAND_0007411                  12
65877  CAND_0065878                  12
6556   CAND_0006557                  12

In [105]:
candidate_text_df[
    ["candidate_id", "professional_score"]
].sort_values(
    "professional_score",
    ascending=True
).head(20)

       candidate_id  professional_score
33949  CAND_0033950                  -4
47758  CAND_0047759                  -4
99267  CAND_0099268                  -4
23544  CAND_0023545                  -4
91991  CAND_0091992                  -4
42128  CAND_0042129                  -4
91370  CAND_0091371                  -4
46483  CAND_0046484                  -4
9678   CAND_0009679                  -4
68224  CAND_0068225                  -4
78262  CAND_0078263                  -4
38463  CAND_0038464                  -4
79200  CAND_0079201                  -4
44318  CAND_0044319                  -4
51303  CAND_0051304                  -4
47158  CAND_0047159                  -4
66164  CAND_0066165                  -4
16042  CAND_0016043                  -4
84086  CAND_0084087                  -4
95550  CAND_0095551                  -3

In [106]:
cand_id = "CAND_0033950"

with open(link, "r", encoding="utf-8") as f:

    for line in f:

        c = json.loads(line)

        if c["candidate_id"] == cand_id:

            print("TITLE:", c["profile"]["current_title"])
            print()
            print(c["profile"]["summary"])
            break

TITLE: Marketing Manager

Marketing Manager with 2.7+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can augment my work. I've been taking online courses on RAG and vector databases, experimenting with LangChain and the OpenAI API for side projects, and exploring how LLMs can streamline workflows in my current function. Open to roles that combine my existing domain experience with emerging AI technologies — I think the most interesting opportunities are at this intersection. Looking for positions where I can contribute both my functional expertise and grow my AI capabilities.

## Final hybrid ranking

In [107]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

candidate_text_df["professional_score_norm"] = (
    scaler.fit_transform(
        candidate_text_df[["professional_score"]]
    )
)

In [108]:
final_df = final_df.merge(
    candidate_text_df[
        ["candidate_id", "professional_score_norm"]
    ],
    on="candidate_id",
    how="left"
)

In [109]:
final_df["final_score_v3"] = (
      0.40 * final_df["semantic_score"]
    + 0.25 * final_df["behavior_score"]
    + 0.15 * final_df["production_evidence_norm"]
    + 0.20 * final_df["professional_score_norm"]
)

In [110]:
top100_v3 = (
    final_df
    .sort_values(
        "final_score_v3",
        ascending=False
    )
    .head(100)
)

In [111]:
top100_v3["title"].value_counts()

title
Applied ML Engineer                 15
AI Engineer                         12
Search Engineer                     12
Recommendation Systems Engineer     11
Machine Learning Engineer           10
NLP Engineer                         7
Senior Data Scientist                7
Senior NLP Engineer                  6
Senior Machine Learning Engineer     5
Staff Machine Learning Engineer      5
Senior AI Engineer                   4
Senior Applied Scientist             3
Lead AI Engineer                     2
Junior ML Engineer                   1
Name: count, dtype: int64

In [112]:
top100_v3[
    top100_v3["title"].isin([
        "HR Manager",
        "Civil Engineer",
        "Marketing Manager",
        "Operations Manager"
    ])
]

Empty DataFrame
Columns: [candidate_id, title, production_score, production_score_norm, behavior_score, final_score, jd_score_norm, production_evidence_norm, semantic_score, final_score_v2, professional_score_norm, final_score_v3]
Index: []

## Top 20 candidates

In [113]:
top20_v3 = top100_v3.head(20)

top20_v3[
    [
        "candidate_id",
        "title",
        "semantic_score",
        "behavior_score",
        "professional_score_norm",
        "final_score_v3"
    ]
]

,candidate_id,title,semantic_score,behavior_score,professional_score_norm,final_score_v3
39753,CAND_0039754,Senior Applied Scientist,0.603239,0.790729,1.000000,0.788978
55904,CAND_0055905,Senior Machine Learning Engineer,0.593365,0.663218,1.000000,0.729466
77336,CAND_0077337,Staff Machine Learning Engineer,0.590700,0.768175,0.947368,0.728324
5259,CAND_0005260,Senior NLP Engineer,0.578742,0.675718,1.000000,0.726742
86021,CAND_0086022,Senior Applied Scientist,0.580495,0.618856,0.947368,0.710596
11686,CAND_0011687,Senior NLP Engineer,0.575021,0.730491,0.842105,0.707368
81845,CAND_0081846,Lead AI Engineer,0.594343,0.613278,0.947368,0.706846
33860,CAND_0033861,Senior NLP Engineer,0.596078,0.499643,1.000000,0.705447
44882,CAND_0044883,AI Engineer,0.562733,0.771505,0.842105,0.704812
55991,CAND_0055992,AI Engineer,0.579351,0.775639,0.842105,0.704597
18498,CAND_0018499,Senior Machine Learning Engineer,0.557288,0.690833,0.894737,0.700887
46063,CAND_0046064,Senior NLP Engineer,0.576020,0.574703,0.947368,0.697768
5648,CAND_0005649,Senior Data Scientist,0.535754,0.714782,0.842105,0.687734
93546,CAND_0093547,Senior Machine Learning Engineer,0.585592,0.648654,0.842105,0.683242
46524,CAND_0046525,Senior Machine Learning Engineer,0.595146,0.688374,0.842105,0.681204
2024,CAND_0002025,Senior AI Engineer,0.612076,0.702500,0.736842,0.678350
83306,CAND_0083307,Search Engineer,0.560539,0.667414,0.842105,0.677911
8424,CAND_0008425,Senior NLP Engineer,0.591396,0.634755,0.894737,0.676826
10256,CAND_0010257,Senior Data Scientist,0.525403,0.730706,0.894737,0.674417
79386,CAND_0079387,AI Engineer,0.497897,0.706651,0.842105,0.670558

## Last 10 candidates

In [114]:
top100_v3.tail(10)[
    [
        "candidate_id",
        "title",
        "final_score_v3"
    ]
]

       candidate_id                            title  final_score_v3
18548  CAND_0018549  Recommendation Systems Engineer        0.587500
49895  CAND_0049896                  Search Engineer        0.586983
57562  CAND_0057563                     NLP Engineer        0.586371
93330  CAND_0093331                     NLP Engineer        0.586282
77284  CAND_0077285  Recommendation Systems Engineer        0.585824
89551  CAND_0089552        Machine Learning Engineer        0.584516
81052  CAND_0081053                     NLP Engineer        0.584095
61264  CAND_0061265  Recommendation Systems Engineer        0.583989
44221  CAND_0044222                      AI Engineer        0.583708
59503  CAND_0059504               Junior ML Engineer        0.583705

## Counting tittle categories

In [115]:
top100_v3["title"].value_counts().head(20)

title
Applied ML Engineer                 15
AI Engineer                         12
Search Engineer                     12
Recommendation Systems Engineer     11
Machine Learning Engineer           10
NLP Engineer                         7
Senior Data Scientist                7
Senior NLP Engineer                  6
Senior Machine Learning Engineer     5
Staff Machine Learning Engineer      5
Senior AI Engineer                   4
Senior Applied Scientist             3
Lead AI Engineer                     2
Junior ML Engineer                   1
Name: count, dtype: int64

In [116]:
top100_v3[
    [
        "candidate_id",
        "title",
        "semantic_score",
        "behavior_score",
        "production_evidence_norm",
        "professional_score_norm",
        "final_score_v3"
    ]
]

,candidate_id,title,semantic_score,behavior_score,production_evidence_norm,professional_score_norm,final_score_v3
39753,CAND_0039754,Senior Applied Scientist,0.603239,0.790729,1.000000,1.000000,0.788978
55904,CAND_0055905,Senior Machine Learning Engineer,0.593365,0.663218,0.842105,1.000000,0.729466
77336,CAND_0077337,Staff Machine Learning Engineer,0.590700,0.768175,0.736842,0.947368,0.728324
5259,CAND_0005260,Senior NLP Engineer,0.578742,0.675718,0.842105,1.000000,0.726742
86021,CAND_0086022,Senior Applied Scientist,0.580495,0.618856,0.894737,0.947368,0.710596
...,...,...,...,...,...,...,...
89551,CAND_0089552,Machine Learning Engineer,0.529794,0.585128,0.736842,0.578947,0.584516
81052,CAND_0081053,NLP Engineer,0.476437,0.616186,0.684211,0.684211,0.584095
61264,CAND_0061265,Recommendation Systems Engineer,0.435574,0.565353,0.736842,0.789474,0.583989
44221,CAND_0044222,AI Engineer,0.548674,0.604325,0.578947,0.631579,0.583708
59503,CAND_0059504,Junior ML Engineer,0.536292,0.771488,0.473684,0.526316,0.583705

## Randomly inspect 20 candidates from top 100

In [117]:
import random

sample_ids = set(
    top100_v3["candidate_id"].sample(
        20,
        random_state=42
    )
)

with open(link, "r", encoding="utf-8") as f:

    for line in f:

        c = json.loads(line)

        if c["candidate_id"] in sample_ids:

            print("=" * 120)

            print("ID:", c["candidate_id"])
            print("TITLE:", c["profile"]["current_title"])
            print("HEADLINE:", c["profile"]["headline"])

            print("\nSUMMARY:")
            print(c["profile"]["summary"])

            print("\nSKILLS:")
            print([s["name"] for s in c["skills"][:20]])

            print("\n")

========================================================================================================================
ID: CAND_0001610
TITLE: Machine Learning Engineer
HEADLINE: Machine Learning Engineer | Applied ML | Building intelligent products

SUMMARY:
Machine learning engineer with 5.2 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I built our semantic search infrastructure from scratch — sentence-transformers, FAISS, the works. I've spent enough time debugging production ranking issues to know which signals matter and which are noise. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['Speech Recognition', 'Haystack', 'Deep Learning', 'Kubeflow', 'Pinecone', 'Salesforce CRM', 'Feature Engineering', 'scikit-learn', 'Fine-tuning LLMs', 'Data Science', 'Milvus', 'Sentence Transformers', 'Reinforcement Learning', 'Information Retrieval', 'NLP', 'PyTorch', 'Computer Vision', 'FAISS']


========================================================================================================================
ID: CAND_0005649
TITLE: Senior Data Scientist
HEADLINE: Senior Data Scientist | Search, Ranking & Retrieval

SUMMARY:
Machine learning engineer with 7.4 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I built our semantic search infrastructure from scratch — sentence-transformers, FAISS, the works. Along the way I've gotten comfortable with the operational side — A/B testing, drift monitoring, retraining schedules. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['Haystack', 'Redis', 'Prompt Engineering', 'Object Detection', 'Deep Learning', 'TensorFlow', 'Fine-tuning LLMs', 'Recommendation Systems', 'QLoRA', 'OpenCV', 'Semantic Search', 'Weaviate', 'scikit-learn', 'RAG', 'Microservices', 'Information Retrieval', 'Kubeflow']


========================================================================================================================
ID: CAND_0010257
TITLE: Senior Data Scientist
HEADLINE: Senior Data Scientist | Applied ML | Building intelligent products

SUMMARY:
Machine learning engineer with 6.5 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I led the team that migrated our keyword-search-based product to embedding-based retrieval. I care a lot about evaluation rigor — too many teams ship models without offline benchmarks they trust. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['Milvus', 'TensorFlow', 'MLflow', 'Python', 'Forecasting', 'OpenSearch', 'Qdrant', 'JavaScript', 'ASR', 'Machine Learning', 'Feature Engineering', 'Image Classification', 'Recommendation Systems', 'pgvector', 'Rust']


========================================================================================================================
ID: CAND_0016163
TITLE: Applied ML Engineer
HEADLINE: Applied ML Engineer | Applied ML | Building intelligent products

SUMMARY:
Machine learning engineer with 6.7 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I led the team that migrated our keyword-search-based product to embedding-based retrieval. I've spent enough time debugging production ranking issues to know which signals matter and which are noise. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['Hugging Face Transformers', 'Computer Vision', 'gRPC', 'Time Series', 'Weaviate', 'CNN', 'Deep Learning', 'TensorFlow', 'ASR', 'Embeddings', 'Tailwind', 'Reinforcement Learning', 'LoRA', 'pgvector', 'Statistical Modeling', 'Pinecone', 'Machine Learning']


========================================================================================================================
ID: CAND_0018499
TITLE: Senior Machine Learning Engineer
HEADLINE: Senior Machine Learning Engineer | Building AI-native search & ranking systems

SUMMARY:
Senior AI engineer with 7.2 years of hands-on experience building production ML systems, with a focus on search, retrieval, and ranking. Most recently, I designed the company's first hybrid retrieval system combining BM25 with dense vector recall, serving 50M+ queries per month. My day-to-day work spans embedding model selection and fine-tuning, hybrid retrieval architecture, learning-to-rank, behavioral-signal integration, and the offline/online evaluation that ties it all together. I've shipped systems in both early-stage product companies and at larger scale, and I've spent enough time on both that I know which tradeoffs apply where. I have strong opinions about when LLMs are the right hammer and when classical IR is — usually it's both. Currently exploring my next move — looking for senior IC or tech-lead roles where I can own the intelligence layer end-to-end.

SKILLS:
['Deep Learning', 'Weaviate', 'Recommendation Systems', 'scikit-learn', 'Diffusion Models', 'Pinecone', 'Information Retrieval', 'Milvus', 'QLoRA', 'RAG', 'Embeddings', 'Learning to Rank', 'CNN', 'Go', 'BM25', 'LangChain', 'Weights & Biases']


========================================================================================================================
ID: CAND_0018549
TITLE: Recommendation Systems Engineer
HEADLINE: Recommendation Systems Engineer | ML, NLP, Recommendation Systems

SUMMARY:
Machine learning engineer with 6.8 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I led the team that migrated our keyword-search-based product to embedding-based retrieval. I've learned that most retrieval problems are actually evaluation problems in disguise. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['Computer Vision', 'Weaviate', 'Kubernetes', 'Elasticsearch', 'BigQuery', 'LangChain', 'Qdrant', 'Milvus', 'Fine-tuning LLMs', 'Speech Recognition', 'scikit-learn', 'Time Series', 'Prompt Engineering', 'OpenSearch']


========================================================================================================================
ID: CAND_0020877
TITLE: Applied ML Engineer
HEADLINE: Applied ML Engineer | Applied ML | Building intelligent products

SUMMARY:
Machine learning engineer with 5.1 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I shipped our first RAG-based feature this year and now own the eval framework for it. I care a lot about evaluation rigor — too many teams ship models without offline benchmarks they trust. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['QLoRA', 'Kubeflow', 'YOLO', 'Elasticsearch', 'PyTorch', 'OpenSearch', 'Information Retrieval', 'Forecasting', 'Statistical Modeling', 'LlamaIndex', 'Weaviate', 'Deep Learning', 'PEFT', 'Milvus', 'scikit-learn', 'Qdrant', 'Illustrator', 'Java']


========================================================================================================================
ID: CAND_0022812
TITLE: Applied ML Engineer
HEADLINE: Applied ML Engineer | Applied ML | Building intelligent products

SUMMARY:
Machine learning engineer with 4.5 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I built our semantic search infrastructure from scratch — sentence-transformers, FAISS, the works. I've learned that most retrieval problems are actually evaluation problems in disguise. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['Weaviate', 'Pinecone', 'LoRA', 'Prompt Engineering', 'Qdrant', 'JavaScript', 'NLP', 'pgvector', 'MLOps', 'LLMs', 'Feature Engineering', 'Forecasting', 'TensorFlow', 'Hadoop', 'Sentence Transformers', 'LangChain', 'Spark', 'GANs', 'Reinforcement Learning']


========================================================================================================================
ID: CAND_0024620
TITLE: AI Engineer
HEADLINE: AI Engineer | ML, NLP, Recommendation Systems

SUMMARY:
Machine learning engineer with 5.9 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I led the team that migrated our keyword-search-based product to embedding-based retrieval. I care a lot about evaluation rigor — too many teams ship models without offline benchmarks they trust. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['Statistical Modeling', 'Object Detection', 'Semantic Search', 'BM25', 'Information Retrieval', 'Prompt Engineering', 'Diffusion Models', 'Feature Engineering', 'React', 'Python', 'LlamaIndex', 'PEFT', 'Recommendation Systems', 'Elasticsearch', 'QLoRA', 'Haystack']


========================================================================================================================
ID: CAND_0030031
TITLE: AI Engineer
HEADLINE: AI Engineer | ML, NLP, Recommendation Systems

SUMMARY:
Machine learning engineer with 5.7 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I shipped our first RAG-based feature this year and now own the eval framework for it. I've spent enough time debugging production ranking issues to know which signals matter and which are noise. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['Information Retrieval', 'PyTorch', 'Object Detection', 'Python', 'NLP', 'RAG', 'OpenCV', 'LoRA', 'QLoRA', 'BM25', 'Time Series', 'Sentence Transformers', 'YOLO', 'Milvus', 'Vector Search', 'scikit-learn']


========================================================================================================================
ID: CAND_0030953
TITLE: Search Engineer
HEADLINE: Search Engineer | ML, NLP, Recommendation Systems

SUMMARY:
Machine learning engineer with 7.8 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I led the team that migrated our keyword-search-based product to embedding-based retrieval. Along the way I've gotten comfortable with the operational side — A/B testing, drift monitoring, retraining schedules. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['TTS', 'MLOps', 'Learning to Rank', 'Databricks', 'Time Series', 'ASR', 'Qdrant', 'Reinforcement Learning', 'Python', 'Hugging Face Transformers', 'pgvector', 'Weaviate', 'RAG', 'LangChain']


========================================================================================================================
ID: CAND_0039754
TITLE: Senior Applied Scientist
HEADLINE: Senior Applied Scientist | Building AI-native search & ranking systems

SUMMARY:
Senior AI engineer with 8.3 years of hands-on experience building production ML systems, with a focus on search, retrieval, and ranking. Most recently, I rebuilt the candidate-JD matching pipeline from scratch, taking it from 0.72 to 0.91 NDCG@10, serving 50M+ queries per month. My day-to-day work spans embedding model selection and fine-tuning, hybrid retrieval architecture, learning-to-rank, behavioral-signal integration, and the offline/online evaluation that ties it all together. I've shipped systems in both early-stage product companies and at larger scale, and I've spent enough time on both that I know which tradeoffs apply where. I believe most ranking problems are solved by careful feature engineering and rigorous eval, not by bigger models. Currently exploring my next move — looking for senior IC or tech-lead roles where I can own the intelligence layer end-to-end.

SKILLS:
['Fine-tuning LLMs', 'LlamaIndex', 'Qdrant', 'Reinforcement Learning', 'NLP', 'Statistical Modeling', 'Kubeflow', 'ASR', 'OpenSearch', 'Deep Learning', 'Machine Learning', 'LLMs', 'BM25', 'Weaviate', 'Python', 'TensorFlow', 'CI/CD', 'pgvector', 'Speech Recognition', 'Elasticsearch']


========================================================================================================================
ID: CAND_0039838
TITLE: Recommendation Systems Engineer
HEADLINE: Recommendation Systems Engineer | Applied ML | Building intelligent products

SUMMARY:
Machine learning engineer with 4.9 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I built our semantic search infrastructure from scratch — sentence-transformers, FAISS, the works. I care a lot about evaluation rigor — too many teams ship models without offline benchmarks they trust. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['MLOps', 'Computer Vision', 'Embeddings', 'Semantic Search', 'LangChain', 'Flask', 'LoRA', 'RAG', 'Milvus', 'Hugging Face Transformers', 'Vector Search', 'QLoRA', 'Reinforcement Learning', 'Kafka', 'Speech Recognition', 'OpenSearch', 'Kubeflow', 'Image Classification', 'Redux', 'Fine-tuning LLMs']


========================================================================================================================
ID: CAND_0041568
TITLE: Search Engineer
HEADLINE: Search Engineer | Search, Ranking & Retrieval

SUMMARY:
Machine learning engineer with 5.2 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I built our semantic search infrastructure from scratch — sentence-transformers, FAISS, the works. Along the way I've gotten comfortable with the operational side — A/B testing, drift monitoring, retraining schedules. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['PEFT', 'Weaviate', 'Angular', 'Feature Engineering', 'GANs', 'Vector Search', 'TensorFlow', 'Computer Vision', 'BM25', 'Semantic Search', 'Recommendation Systems', 'CNN', 'Hugging Face Transformers', 'Spring Boot', 'Reinforcement Learning', 'Qdrant', 'Pinecone', 'Deep Learning']


========================================================================================================================
ID: CAND_0058688
TITLE: AI Engineer
HEADLINE: AI Engineer | Applied ML | Building intelligent products

SUMMARY:
Machine learning engineer with 6.7 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, my main project for the last 18 months has been the recommendation system that powers our discovery feed. Along the way I've gotten comfortable with the operational side — A/B testing, drift monitoring, retraining schedules. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:
['OpenCV', 'CNN', 'scikit-learn', 'Object Detection', 'LlamaIndex', 'Computer Vision', 'Embeddings', 'Snowflake', 'TensorFlow', 'Diffusion Models', 'Information Retrieval', 'Milvus', 'Image Classification', 'Machine Learning', 'QLoRA', 'PostgreSQL', 'Semantic Search']


========================================================================================================================
ID: CAND_0065195
TITLE: Search Engineer
HEADLINE: Search Engineer | Search, Ranking & Retrieval

SUMMARY:
Machine learning engineer with 5.1 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I led the team that migrated our keyword-search-based product to embedding-based retrieval. I care a lot about evaluation rigor — too many teams ship models without offline benchmarks they trust. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.

SKILLS:

## Top 100 candidates

In [118]:
top100_ids = set(top100_v3["candidate_id"])

rows = []

with open(link, "r", encoding="utf-8") as f:

    for line in f:

        c = json.loads(line)

        if c["candidate_id"] in top100_ids:

            rows.append({
                "candidate_id": c["candidate_id"],
                "title": c["profile"]["current_title"],
                "headline": c["profile"]["headline"],
                "summary": c["profile"]["summary"],
                "skills": ", ".join(
                    [s["name"] for s in c["skills"][:20]]
                )
            })

top100_audit = pd.DataFrame(rows)

top100_audit

,candidate_id,title,headline,summary,skills
0,CAND_0001610,Machine Learning Engineer,Machine Learning Engineer | Applied ML | Build...,Machine learning engineer with 5.2 years of ex...,"Speech Recognition, Haystack, Deep Learning, K..."
1,CAND_0002025,Senior AI Engineer,Senior AI Engineer | Building AI-native search...,Senior AI engineer with 5.9 years of hands-on ...,"Diffusion Models, FAISS, TensorFlow, scikit-le..."
2,CAND_0005260,Senior NLP Engineer,"Senior NLP Engineer | LLMs, RAG, Vector Search...",Senior AI engineer with 5.2 years of hands-on ...,"Statistical Modeling, MLOps, Snowflake, Prompt..."
3,CAND_0005538,Senior AI Engineer,Senior Engineer | 5.9+ yrs in production systems,Senior engineer who has spent the last several...,"Project Management, Vector Representations, De..."
4,CAND_0005649,Senior Data Scientist,"Senior Data Scientist | Search, Ranking & Retr...",Machine learning engineer with 7.4 years of ex...,"Haystack, Redis, Prompt Engineering, Object De..."
...,...,...,...,...,...
95,CAND_0093547,Senior Machine Learning Engineer,Senior Machine Learning Engineer | Building AI...,Senior AI engineer with 6.3 years of hands-on ...,"LLMs, RAG, Python, QLoRA, Kubeflow, PEFT, GANs..."
96,CAND_0094759,Lead AI Engineer,Lead AI Engineer | Production ML at scale | 8....,Senior AI engineer with 8.6 years of hands-on ...,"Prompt Engineering, scikit-learn, Hugging Face..."
97,CAND_0095528,Senior Data Scientist,"Senior Data Scientist | Search, Ranking & Retr...",Machine learning engineer with 5.3 years of ex...,"Feature Engineering, OpenSearch, PyTorch, Sema..."
98,CAND_0096142,Applied ML Engineer,"Applied ML Engineer | Search, Ranking & Retrieval",Machine learning engineer with 5.0 years of ex...,"Kubeflow, LoRA, Weaviate, Pinecone, Python, CS..."
99,CAND_0098846,AI Engineer,"AI Engineer | Search, Ranking & Retrieval",Machine learning engineer with 7.6 years of ex...,"YOLO, Kubeflow, Hugging Face Transformers, Had..."

In [119]:
top100_v3.head(20)

,candidate_id,title,production_score,production_score_norm,behavior_score,final_score,jd_score_norm,production_evidence_norm,semantic_score,final_score_v2,professional_score_norm,final_score_v3
39753,CAND_0039754,Senior Applied Scientist,9,0.750000,0.790729,0.833146,1.000000,1.000000,0.603239,0.738838,1.000000,0.788978
55904,CAND_0055905,Senior Machine Learning Engineer,7,0.583333,0.663218,0.674310,0.833333,0.842105,0.593365,0.664069,1.000000,0.729466
77336,CAND_0077337,Staff Machine Learning Engineer,8,0.666667,0.768175,0.686968,0.666667,0.736842,0.590700,0.673171,0.947368,0.728324
5259,CAND_0005260,Senior NLP Engineer,7,0.583333,0.675718,0.651810,0.750000,0.842105,0.578742,0.660508,1.000000,0.726742
86021,CAND_0086022,Senior Applied Scientist,7,0.583333,0.618856,0.640438,0.750000,0.894737,0.580495,0.654852,0.947368,0.710596
11686,CAND_0011687,Senior NLP Engineer,7,0.583333,0.730491,0.562765,0.416667,0.842105,0.575021,0.675079,0.842105,0.707368
81845,CAND_0081846,Lead AI Engineer,6,0.500000,0.613278,0.622656,0.833333,0.842105,0.594343,0.649576,0.947368,0.706846
33860,CAND_0033861,Senior NLP Engineer,9,0.750000,0.499643,0.649929,0.583333,0.947368,0.596078,0.637406,1.000000,0.705447
44882,CAND_0044883,AI Engineer,10,0.833333,0.771505,0.820968,0.833333,0.789474,0.562733,0.670713,0.842105,0.704812
55991,CAND_0055992,AI Engineer,11,0.916667,0.775639,0.888461,0.916667,0.736842,0.579351,0.669735,0.842105,0.704597
18498,CAND_0018499,Senior Machine Learning Engineer,7,0.583333,0.690833,0.654833,0.750000,0.842105,0.557288,0.654315,0.894737,0.700887
46063,CAND_0046064,Senior NLP Engineer,10,0.833333,0.574703,0.806607,0.916667,0.894737,0.576020,0.639368,0.947368,0.697768
5648,CAND_0005649,Senior Data Scientist,10,0.833333,0.714782,0.809623,0.833333,0.842105,0.535754,0.650733,0.842105,0.687734
93546,CAND_0093547,Senior Machine Learning Engineer,7,0.583333,0.648654,0.546397,0.416667,0.789474,0.585592,0.645287,0.842105,0.683242
46524,CAND_0046525,Senior Machine Learning Engineer,7,0.583333,0.688374,0.654341,0.750000,0.684211,0.595146,0.640927,0.842105,0.681204
2024,CAND_0002025,Senior AI Engineer,7,0.583333,0.702500,0.507167,0.250000,0.736842,0.612076,0.664156,0.736842,0.678350
83306,CAND_0083307,Search Engineer,8,0.666667,0.667414,0.716816,0.833333,0.789474,0.560539,0.638388,0.842105,0.677911
8424,CAND_0008425,Senior NLP Engineer,8,0.666667,0.634755,0.660284,0.666667,0.684211,0.591396,0.622967,0.894737,0.676826
10256,CAND_0010257,Senior Data Scientist,7,0.583333,0.730706,0.512808,0.250000,0.684211,0.525403,0.618755,0.894737,0.674417
79386,CAND_0079387,AI Engineer,12,1.000000,0.706651,0.916330,0.916667,0.842105,0.497897,0.629365,0.842105,0.670558

In [120]:
top100_v3.to_csv(
    "top100_final.csv",
    index=False
)

In [121]:
top100_v3 = top100_v3.reset_index(drop=True)

top100_v3["rank"] = top100_v3.index + 1

In [122]:
top100_v3["score"] = top100_v3["final_score_v3"]

In [123]:
def create_reason(row):

    return (
        f"{row['title']}; "
        f"semantic match {row['semantic_score']:.2f}; "
        f"behavior score {row['behavior_score']:.2f}; "
        f"strong production and professional AI experience."
    )

top100_v3["reasoning"] = top100_v3.apply(
    create_reason,
    axis=1
)

In [124]:
submission = top100_v3[
    [
        "candidate_id",
        "rank",
        "score",
        "reasoning"
    ]
]

submission.to_csv(
    "submission.csv",
    index=False
)

In [125]:
top100_v3.columns

Index(['candidate_id', 'title', 'production_score', 'production_score_norm',
       'behavior_score', 'final_score', 'jd_score_norm',
       'production_evidence_norm', 'semantic_score', 'final_score_v2',
       'professional_score_norm', 'final_score_v3', 'rank', 'score',
       'reasoning'],
      dtype='object')

In [126]:
top100_v3[
    ["candidate_id", "reasoning"]
].head(10)

   candidate_id                                          reasoning
0  CAND_0039754  Senior Applied Scientist; semantic match 0.60;...
1  CAND_0055905  Senior Machine Learning Engineer; semantic mat...
2  CAND_0077337  Staff Machine Learning Engineer; semantic matc...
3  CAND_0005260  Senior NLP Engineer; semantic match 0.58; beha...
4  CAND_0086022  Senior Applied Scientist; semantic match 0.58;...
5  CAND_0011687  Senior NLP Engineer; semantic match 0.58; beha...
6  CAND_0081846  Lead AI Engineer; semantic match 0.59; behavio...
7  CAND_0033861  Senior NLP Engineer; semantic match 0.60; beha...
8  CAND_0044883  AI Engineer; semantic match 0.56; behavior sco...
9  CAND_0055992  AI Engineer; semantic match 0.58; behavior sco...

In [127]:
def create_reason(row):

    title = row["title"]

    if "NLP" in title:
        return (
            "Strong NLP and semantic-search background with evidence of production AI systems, "
            "ranking pipelines, and high relevance to the target role."
        )

    elif "Search" in title:
        return (
            "Experienced in retrieval, ranking, and search infrastructure with strong alignment "
            "to the job requirements and demonstrated production impact."
        )

    elif "Machine Learning" in title or "AI Engineer" in title:
        return (
            "Strong applied AI and machine learning experience with production deployment exposure "
            "and high semantic alignment to the job description."
        )

    else:
        return (
            "Demonstrates strong AI expertise, production experience, and overall fit for the role."
        )

In [128]:
top100_v3["reasoning"] = top100_v3.apply(
    create_reason,
    axis=1
)

In [129]:
submission = top100_v3[
    ["candidate_id", "rank", "score", "reasoning"]
]

submission.head(20)

,candidate_id,rank,score,reasoning
0,CAND_0039754,1,0.788978,"Demonstrates strong AI expertise, production e..."
1,CAND_0055905,2,0.729466,Strong applied AI and machine learning experie...
2,CAND_0077337,3,0.728324,Strong applied AI and machine learning experie...
3,CAND_0005260,4,0.726742,Strong NLP and semantic-search background with...
4,CAND_0086022,5,0.710596,"Demonstrates strong AI expertise, production e..."
5,CAND_0011687,6,0.707368,Strong NLP and semantic-search background with...
6,CAND_0081846,7,0.706846,Strong applied AI and machine learning experie...
7,CAND_0033861,8,0.705447,Strong NLP and semantic-search background with...
8,CAND_0044883,9,0.704812,Strong applied AI and machine learning experie...
9,CAND_0055992,10,0.704597,Strong applied AI and machine learning experie...
10,CAND_0018499,11,0.700887,Strong applied AI and machine learning experie...
11,CAND_0046064,12,0.697768,Strong NLP and semantic-search background with...
12,CAND_0005649,13,0.687734,"Demonstrates strong AI expertise, production e..."
13,CAND_0093547,14,0.683242,Strong applied AI and machine learning experie...
14,CAND_0046525,15,0.681204,Strong applied AI and machine learning experie...
15,CAND_0002025,16,0.678350,Strong applied AI and machine learning experie...
16,CAND_0083307,17,0.677911,"Experienced in retrieval, ranking, and search ..."
17,CAND_0008425,18,0.676826,Strong NLP and semantic-search background with...
18,CAND_0010257,19,0.674417,"Demonstrates strong AI expertise, production e..."
19,CAND_0079387,20,0.670558,Strong applied AI and machine learning experie...

In [130]:
candidate_text_df.columns

Index(['candidate_id', 'candidate_text', 'production_evidence',
       'production_evidence_norm', 'professional_score',
       'professional_score_norm'],
      dtype='object')

In [131]:
import json

profile_lookup = {}

with open(link, "r", encoding="utf-8") as f:

    for line in f:

        c = json.loads(line)

        profile_lookup[c["candidate_id"]] = {
            "title": c["profile"]["current_title"],
            "headline": c["profile"]["headline"],
            "summary": c["profile"]["summary"]
        }

print("Loaded", len(profile_lookup))

Loaded 100000

In [180]:
import re

def create_reason(candidate_id):

    profile = profile_lookup[candidate_id]

    title = profile["title"]
    headline = profile["headline"]
    summary = profile["summary"]

    text = (headline + " " + summary).lower()

    reason = ""

    # ---------------------------------------
    # Years of Experience
    # ---------------------------------------
    years = ""

    match = re.search(r'(\d+(\.\d+)?)\+?\s*years', summary)

    if match:
        years = match.group(1)

    if years:
        reason += f"{title} with {years}+ years of professional experience. "
    else:
        reason += f"{title}. "

    # ---------------------------------------
    # Domain
    # ---------------------------------------

    if "nlp" in text:
        reason += "Strong background in Natural Language Processing. "

    elif "backend" in text:
        reason += "Strong backend engineering and data infrastructure experience. "

    elif "machine learning" in text:
        reason += "Strong machine learning background. "

    elif "data scientist" in text:
        reason += "Strong applied data science experience. "

    elif "computer vision" in text:
        reason += "Experience building computer vision solutions. "

    # ---------------------------------------
    # AI Technologies
    # ---------------------------------------

    tech = []

    technologies = [
        "langchain",
        "llamaindex",
        "rag",
        "semantic search",
        "embeddings",
        "faiss",
        "pinecone",
        "bm25",
        "tensorflow",
        "pytorch",
        "llms",
        "opensearch",
        "weaviate",
        "qdrant",
        "milvus",
        "recommendation",
        "retrieval",
        "ranking"
    ]

    for t in technologies:
        if t in text:
            tech.append(t.title())

    tech = tech[:4]

    if tech:
        reason += (
            "Demonstrates expertise in "
            + ", ".join(tech)
            + ". "
        )

    # ---------------------------------------
    # Production Experience
    # ---------------------------------------

    if any(word in text for word in [
        "production",
        "built",
        "deployed",
        "designed",
        "owned",
        "shipped"
    ]):

        reason += (
            "The profile highlights hands-on experience delivering production-grade AI systems. "
        )

    # ---------------------------------------
    # Evaluation
    # ---------------------------------------

    if any(word in text for word in [
        "ndcg",
        "mrr",
        "evaluation",
        "offline",
        "online"
    ]):

        reason += (
            "Demonstrates experience improving retrieval quality using evaluation metrics. "
        )

    # ---------------------------------------
    # Transition to AI
    # ---------------------------------------

    if any(word in text for word in [
        "transition",
        "transitioning",
        "learning",
        "exploring",
        "completed",
        "self-directed"
    ]):

        reason += (
            "Shows continuous learning and active transition toward modern AI technologies. "
        )

    # ---------------------------------------
    # Final Recommendation
    # ---------------------------------------

    reason += (
        "Overall, the candidate demonstrates strong technical capability and relevant experience, making the profile well aligned with the target role."
    )

    return reason

In [181]:
top100_v3["reasoning"] = top100_v3["candidate_id"].apply(create_reason)

In [182]:
top100_v3["reasoning"].nunique()

97

In [183]:
top100_v3[
    ["candidate_id", "title", "reasoning"]
].sample(10, random_state=42)

,candidate_id,title,reasoning
83,CAND_0020877,Applied ML Engineer,Applied ML Engineer with 5.1+ years of profess...
53,CAND_0058688,AI Engineer,AI Engineer with 6.7+ years of professional ex...
70,CAND_0001610,Machine Learning Engineer,Machine Learning Engineer with 5.2+ years of p...
45,CAND_0065195,Search Engineer,Search Engineer with 5.1+ years of professiona...
44,CAND_0084819,Search Engineer,Search Engineer with 4.5+ years of professiona...
39,CAND_0080766,Staff Machine Learning Engineer,Staff Machine Learning Engineer. Demonstrates ...
22,CAND_0094759,Lead AI Engineer,Lead AI Engineer with 8.6+ years of profession...
80,CAND_0041568,Search Engineer,Search Engineer with 5.2+ years of professiona...
10,CAND_0018499,Senior Machine Learning Engineer,Senior Machine Learning Engineer with 7.2+ yea...
0,CAND_0039754,Senior Applied Scientist,Senior Applied Scientist with 8.3+ years of pr...

In [184]:
top100_v3[
    ["candidate_id", "reasoning"]
].head(10)

   candidate_id                                          reasoning
0  CAND_0039754  Senior Applied Scientist with 8.3+ years of pr...
1  CAND_0055905  Senior Machine Learning Engineer with 8.1+ yea...
2  CAND_0077337  Staff Machine Learning Engineer with 7.0+ year...
3  CAND_0005260  Senior NLP Engineer with 5.2+ years of profess...
4  CAND_0086022  Senior Applied Scientist with 5.3+ years of pr...
5  CAND_0011687  Senior NLP Engineer with 7.8+ years of profess...
6  CAND_0081846  Lead AI Engineer with 6.7+ years of profession...
7  CAND_0033861  Senior NLP Engineer with 8.0+ years of profess...
8  CAND_0044883  AI Engineer with 6.3+ years of professional ex...
9  CAND_0055992  AI Engineer with 6.8+ years of professional ex...

# Top final 100 candidates

In [187]:
submission = top100_v3[
    ["candidate_id", "rank", "score", "reasoning"]
]

In [163]:
submission

,candidate_id,rank,score,reasoning
0,CAND_0039754,1,0.788978,Senior Applied Scientist demonstrates expertis...
1,CAND_0055905,2,0.729466,Senior Machine Learning Engineer demonstrates ...
2,CAND_0077337,3,0.728324,Staff Machine Learning Engineer demonstrates e...
3,CAND_0005260,4,0.726742,Senior NLP Engineer demonstrates expertise in ...
4,CAND_0086022,5,0.710596,Senior Applied Scientist demonstrates expertis...
...,...,...,...,...
95,CAND_0089552,96,0.584516,Machine Learning Engineer demonstrates experti...
96,CAND_0081053,97,0.584095,NLP Engineer demonstrates expertise in ranking...
97,CAND_0061265,98,0.583989,Recommendation Systems Engineer demonstrates e...
98,CAND_0044222,99,0.583708,AI Engineer demonstrates expertise in retrieva...
99,CAND_0059504,100,0.583705,Junior ML Engineer demonstrates expertise in r...

In [188]:
submission.shape

(100, 4)

In [165]:
submission.isnull().sum()

candidate_id    0
rank            0
score           0
reasoning       0
dtype: int64

In [189]:
submission["rank"].min(), submission["rank"].max()

(1, 100)

In [190]:
submission.to_csv(
    "submission.csv",
    index=False
)

In [191]:
candidate_embeddings

array([[-0.10047323, -0.11540761,  0.04442741, ...,  0.0113055 ,
        -0.02986764,  0.01983429],
       [-0.11493346, -0.09655489,  0.034912  , ..., -0.04738029,
        -0.02903978,  0.0212522 ],
       [-0.10099871, -0.08497132,  0.03615238, ..., -0.03268193,
        -0.02258268,  0.01384339],
       ...,
       [-0.10645287, -0.06985074,  0.02218114, ..., -0.04269923,
        -0.05276887, -0.01547933],
       [-0.09538174, -0.08738052,  0.00560658, ...,  0.00498631,
         0.02989421,  0.02684305],
       [-0.05356141, -0.07658286,  0.05476036, ..., -0.03805376,
        -0.04978667,  0.011848  ]], dtype=float32)

In [192]:
candidate_embeddings.shape

(100000, 384)

In [193]:
print(type(candidate_embeddings))

<class 'numpy.ndarray'>

In [194]:
!mkdir -p /content/drive/MyDrive/hackathon

In [195]:
import numpy as np

np.save(
    "/content/drive/MyDrive/hackathon/candidate_embeddings.npy",
    candidate_embeddings
)

print("Saved successfully")

Saved successfully

In [196]:
candidate_embeddings.shape

(100000, 384)

In [197]:
candidate_embeddings.nbytes / (1024**2)

146.484375

In [198]:
candidate_text_df.to_csv(
    "/content/drive/MyDrive/hackathon/candidate_text_df.csv",
    index=False
)

final_df.to_csv(
    "/content/drive/MyDrive/hackathon/final_df.csv",
    index=False
)

submission.to_csv(
    "/content/drive/MyDrive/hackathon/submission.csv",
    index=False
)

In [199]:
!ls -lh /content/drive/MyDrive/hackathon

total 352M
-rw------- 1 root root 147M Jun 25 15:54 candidate_embeddings.npy
-rw------- 1 root root 189M Jun 25 15:55 candidate_text_df.csv
-rw------- 1 root root  17M Jun 25 15:55 final_df.csv
-rw------- 1 root root  54K Jun 25 15:55 submission.csv

In [200]:
print(model)

SentenceTransformer(
  (0): Transformer({'transformer_task': 'feature-extraction', 'modality_config': {'text': {'method': 'forward', 'method_output_name': 'last_hidden_state'}}, 'module_output_name': 'token_embeddings', 'architecture': 'BertModel'})
  (1): Pooling({'embedding_dimension': 384, 'pooling_mode': 'mean', 'include_prompt': True})
  (2): Normalize({})
)

In [201]:
list(final_df.columns)

['candidate_id',
 'title',
 'production_score',
 'production_score_norm',
 'behavior_score',
 'final_score',
 'jd_score_norm',
 'production_evidence_norm',
 'semantic_score',
 'final_score_v2',
 'professional_score_norm',
 'final_score_v3']